#!/usr/bin/env bash
# sync_labels.sh — auto-generated by scripts/gen_prompts/generate.py
# Run once after changing labels in config.yaml:
#   bash scripts/gen_prompts/sync_labels.sh
#
# Requires: gh CLI authenticated with write access to the repo.
# Safe to run repeatedly — uses `gh label edit` if the label already exists.
set -euo pipefail
GH_REPO="cgcardona/maestro"

# Helper: create label if absent, otherwise update color + description.
sync_label() {
  local name="$1" color="$2" desc="$3"
  if gh label list --repo "$GH_REPO" --limit 200 | grep -q "^${name}\b"; then
    gh label edit "$name" --repo "$GH_REPO" --color "$color" --description "$desc"
    echo "  ✏️  updated: $name"
  else
    gh label create "$name" --repo "$GH_REPO" --color "$color" --description "$desc"
    echo "  ✅ created: $name"
  fi
}

echo '── Claim label ──────────────────────────────────────────────'
sync_label 'agent:wip' '0075ca' 'Claimed by a pipeline agent — do not assign manually'

echo '── Project label ────────────────────────────────────────────'
sync_label 'agentception' '8250df' 'AgentCeption — autonomous multi-agent pipeline'

echo '── Phase labels ─────────────────────────────────────────────'
sync_label 'agentception/0-scaffold' '6741d9' 'AgentCeption Phase 0 · Foundation scaffold'
sync_label 'agentception/1-controls' '1098ad' 'AgentCeption Phase 1 · Pipeline controls (kill, pause, spawn)'
sync_label 'agentception/2-telemetry' '0d6efd' 'AgentCeption Phase 2 · Telemetry and observability'
sync_label 'agentception/3-roles' '198754' 'AgentCeption Phase 3 · Role file management and editing'
sync_label 'agentception/4-intelligence' 'f59f00' 'AgentCeption Phase 4 · Pipeline intelligence and DAG'
sync_label 'agentception/5-scaling' 'd63939' 'AgentCeption Phase 5 · Scaling advisor and A/B testing'
sync_label 'agentception/6-generalization' '0ca678' 'AgentCeption Phase 6 · Multi-repo generalization and export'

echo '── Utility labels ───────────────────────────────────────────'
sync_label 'bug' 'd73a4a' 'Something isn'\''t working'
sync_label 'enhancement' 'a2eeef' 'New feature or request'
sync_label 'documentation' '0075ca' 'Improvements or additions to documentation'
sync_label 'testing' '10b981' 'Test coverage — unit, integration, e2e'
sync_label 'mypy' '0ea5e9' 'Type errors or mypy compliance required'
sync_label 'good first issue' '7057ff' 'Good for newcomers'
sync_label 'help wanted' '008672' 'Extra attention is needed'
sync_label 'duplicate' 'cfd3d7' 'This issue or pull request already exists'
sync_label 'wontfix' 'ffffff' 'This will not be worked on'

echo ''
echo '✅ Label sync complete.'
