#!/usr/bin/env bash
# sync_labels.sh — auto-generated by scripts/gen_prompts/generate.py
# Run once after changing labels in config.yaml:
#   bash scripts/gen_prompts/sync_labels.sh
#
# Requires: gh CLI authenticated with write access to the repo.
# Safe to run repeatedly — uses `gh label edit` if the label already exists.
set -euo pipefail
GH_REPO="cgcardona/maestro"

# Helper: create label if absent, otherwise update color + description.
sync_label() {
  local name="$1" color="$2" desc="$3"
  if gh label list --repo "$GH_REPO" --limit 200 | grep -q "^${name}\b"; then
    gh label edit "$name" --repo "$GH_REPO" --color "$color" --description "$desc"
    echo "  ✏️  updated: $name"
  else
    gh label create "$name" --repo "$GH_REPO" --color "$color" --description "$desc"
    echo "  ✅ created: $name"
  fi
}

echo '── Claim label ──────────────────────────────────────────────'
sync_label 'agent:wip' '0075ca' 'Claimed by a pipeline agent — do not assign manually'

echo '── Project label ────────────────────────────────────────────'
sync_label 'agentception' '7c3aed' 'AgentCeption multi-tier agent pipeline dashboard'

echo '── Phase labels ─────────────────────────────────────────────'
sync_label 'agentception/0-scaffold' '1e40af' 'AgentCeption Phase 0 — core scaffold, readers, poller, MVP UI (sequential)'
sync_label 'agentception/1-controls' '1d4ed8' 'AgentCeption Phase 1 — kill/pause/spawn control plane'
sync_label 'agentception/2-telemetry' '0e7490' 'AgentCeption Phase 2 — wave history, cost estimation, timeline'
sync_label 'agentception/3-roles' '065f46' 'AgentCeption Phase 3 — role studio, inline editor, pipeline-config.json'
sync_label 'agentception/4-intelligence' '92400e' 'AgentCeption Phase 4 — dependency DAG, stale claim detector, ticket analyzer'
sync_label 'agentception/5-scaling' '991b1b' 'AgentCeption Phase 5 — auto-scaling advisor, A/B role testing'
sync_label 'agentception/6-generalization' '4c1d95' 'AgentCeption Phase 6 — multi-repo support, template marketplace, standalone repo'

echo '── Utility labels ───────────────────────────────────────────'
sync_label 'bug' 'd73a4a' 'Something isn'\''t working'
sync_label 'enhancement' 'a2eeef' 'New feature or request'
sync_label 'documentation' '0075ca' 'Improvements or additions to documentation'
sync_label 'testing' '10b981' 'Test coverage — unit, integration, e2e'
sync_label 'mypy' '0ea5e9' 'Type errors or mypy compliance required'
sync_label 'good first issue' '7057ff' 'Good for newcomers'
sync_label 'help wanted' '008672' 'Extra attention is needed'
sync_label 'duplicate' 'cfd3d7' 'This issue or pull request already exists'
sync_label 'wontfix' 'ffffff' 'This will not be worked on'

echo ''
echo '✅ Label sync complete.'
