#!/usr/bin/env bash
# sync_labels.sh — auto-generated by scripts/gen_prompts/generate.py
# Run once after changing labels in config.yaml:
#   bash scripts/gen_prompts/sync_labels.sh
#
# Requires: gh CLI authenticated with write access to the repo.
# Safe to run repeatedly — uses `gh label edit` if the label already exists.
set -euo pipefail
GH_REPO="cgcardona/maestro"

# Helper: create label if absent, otherwise update color + description.
sync_label() {
  local name="$1" color="$2" desc="$3"
  if gh label list --repo "$GH_REPO" --limit 200 | grep -q "^${name}\b"; then
    gh label edit "$name" --repo "$GH_REPO" --color "$color" --description "$desc"
    echo "  ✏️  updated: $name"
  else
    gh label create "$name" --repo "$GH_REPO" --color "$color" --description "$desc"
    echo "  ✅ created: $name"
  fi
}

echo '── Claim label ──────────────────────────────────────────────'
sync_label 'agent:wip' '0075ca' 'Claimed by a pipeline agent — do not assign manually'

echo '── Project label ────────────────────────────────────────────'
sync_label 'htmx-migration' 'e65100' 'HTMX migration — server-side rendering rollout for Muse Hub'

echo '── Phase labels ─────────────────────────────────────────────'
sync_label 'htmx/0-foundation' '6741d9' 'HTMX Phase 0 · Foundation — infra helpers, base template, filters'
sync_label 'htmx/1-pages' '1098ad' 'HTMX Phase 1 · Core pages SSR'
sync_label 'htmx/2-main-ui' '0d6efd' 'HTMX Phase 2 · Main UI pages SSR + HTMX filters'
sync_label 'htmx/3-analysis' '198754' 'HTMX Phase 3 · Analysis pages SSR'
sync_label 'htmx/4-canvas' 'f59f00' 'HTMX Phase 4 · Canvas / partial SSR pages'
sync_label 'htmx/5-cleanup' 'd63939' 'HTMX Phase 5 · Cleanup — remove dead JS, audit coverage'

echo '── Utility labels ───────────────────────────────────────────'
sync_label 'bug' 'd73a4a' 'Something isn'\''t working'
sync_label 'enhancement' 'a2eeef' 'New feature or request'
sync_label 'documentation' '0075ca' 'Improvements or additions to documentation'
sync_label 'testing' '10b981' 'Test coverage — unit, integration, e2e'
sync_label 'mypy' '0ea5e9' 'Type errors or mypy compliance required'
sync_label 'good first issue' '7057ff' 'Good for newcomers'
sync_label 'help wanted' '008672' 'Extra attention is needed'
sync_label 'duplicate' 'cfd3d7' 'This issue or pull request already exists'
sync_label 'wontfix' 'ffffff' 'This will not be worked on'

echo ''
echo '✅ Label sync complete.'
