"""Mode-specific prompts: editing, editing-composition, and composing."""

from __future__ import annotations


def editing_prompt(required_single_tool: bool) -> str:
    if required_single_tool:
        return (
            "This request is a single-tool intent.\n"
            "Call exactly ONE tool and then stop.\n"
            "Do not call any additional tools for 'helpful' setup.\n"
        )
    return (
        "This request may require multiple steps.\n"
        "Only use deterministic primitives. Never call generator tools directly.\n"
        "If you would need a generator, ask for confirmation first.\n"
    )


def editing_composition_prompt() -> str:
    """Prompt for composition requests routed through EDITING mode (empty projects).

    When the project has no tracks, composition uses EDITING so that structural
    changes (tracks, regions, instruments, notes) are emitted as tool_call
    events for real-time frontend rendering — the user watches the project
    build out step by step.
    """
    return (
        "COMPOSITION MODE: Create the full project structure and musical content.\n\n"
        "Build the song step by step using the available tools:\n"
        "1. set tempo and key signature for the project\n"
        "2. Create ALL tracks with descriptive names (stori_add_midi_track)\n"
        "3. For EACH track: create a region (stori_add_midi_region), then add notes (stori_add_notes)\n"
        "4. Add insert effects (stori_add_insert_effect) and routing (stori_ensure_bus, stori_add_send)\n"
        "5. Add MIDI CC curves (stori_add_midi_cc) for every cc_curves entry in MidiExpressiveness\n"
        "6. Add pitch bend (stori_add_pitch_bend) for every pitch_bend entry in MidiExpressiveness\n"
        "7. Add automation lanes (stori_add_automation) for every Automation block\n"
        "Steps 4-7 are REQUIRED — never skip them when a MAESTRO PROMPT specifies Effects, "
        "MidiExpressiveness, or Automation.\n\n"

        "══════════════════════════════════════════════════════════════════\n"
        "MAESTRO PROMPT → TOOL CALL TRANSLATION (mandatory, not optional)\n"
        "══════════════════════════════════════════════════════════════════\n"
        "When a MAESTRO PROMPT includes any of the following blocks you MUST translate\n"
        "each entry into the corresponding tool call. Do NOT treat these blocks as\n"
        "decorative prose — they are an execution checklist.\n\n"

        "── EFFECTS BLOCK → stori_add_insert_effect ──────────────────────\n"
        "Call stori_add_insert_effect once per effect per track, AFTER the track is created.\n"
        "  Effects:\n"
        "    drums:\n"
        "      compression/compressor → type='compressor'\n"
        "      room/reverb            → type='reverb'\n"
        "      saturation/tape        → type='overdrive'\n"
        "      eq/equalizer           → type='eq'\n"
        "    bass:\n"
        "      compression            → type='compressor'\n"
        "      saturation/tube/overdrive → type='overdrive'\n"
        "      eq                     → type='eq'\n"
        "      distortion/fuzz        → type='distortion'\n"
        "    chords/keys/pads:\n"
        "      reverb                 → type='reverb' (or route via Reverb bus)\n"
        "      chorus                 → type='chorus'\n"
        "      tremolo                → type='tremolo'\n"
        "      phaser                 → type='phaser'\n"
        "      flanger                → type='flanger'\n"
        "    lead/guitar:\n"
        "      overdrive/cranked amp  → type='overdrive'\n"
        "      distortion             → type='distortion'\n"
        "      delay                  → type='delay'\n"
        "      chorus                 → type='chorus'\n"
        "  Shared buses (use when 2+ tracks share reverb/delay):\n"
        "    stori_ensure_bus(name='Reverb')        ← creates bus, returns busId\n"
        "    stori_add_send(trackId=X, busId=$N.busId, levelDb=-6)  ← one per track\n"
        "    stori_add_send(trackId=Y, busId=$N.busId, levelDb=-9)\n"
        "    Common bus names: 'Reverb', 'Delay', 'Room'\n"
        "    ALWAYS call stori_ensure_bus BEFORE stori_add_send for the same bus.\n"
        "  Style defaults (always add these even without an explicit Effects block):\n"
        "    drums → compressor. Bass → compressor. Pads/lead → reverb or send.\n"
        "    rock/prog  → distortion or overdrive on lead\n"
        "    jazz/soul  → chorus on keys, reverb on all\n"
        "    lo-fi      → filter on drums, chorus on chords\n"
        "    shoegaze   → distortion + chorus + reverb on lead\n\n"

        "── MidiExpressiveness.cc_curves → stori_add_midi_cc ─────────────\n"
        "For EACH entry in cc_curves, call stori_add_midi_cc on the relevant region.\n"
        "Convert 'position: bars N-M' to beat numbers (bar N start = (N-1)×4 beats in 4/4).\n"
        "  Example — cc: 91, from: 15, to: 25, position: bars 1-8, target track: Lead\n"
        "    → stori_add_midi_cc(regionId=LEAD_REGION_ID, cc=91,\n"
        "         events=[{'beat': 0, 'value': 15}, {'beat': 32, 'value': 25}])\n"
        "  Example — cc: 1, value: 20, position: bars 1-16\n"
        "    → stori_add_midi_cc(regionId=REGION_ID, cc=1,\n"
        "         events=[{'beat': 0, 'value': 20}, {'beat': 64, 'value': 20}])\n"
        "  CC number reference:\n"
        "    CC 1  = modulation wheel (vibrato depth)\n"
        "    CC 7  = channel volume\n"
        "    CC 10 = pan position\n"
        "    CC 11 = expression (fine dynamics within volume)\n"
        "    CC 64 = sustain pedal (0=up, 127=down)\n"
        "    CC 71 = filter resonance\n"
        "    CC 74 = filter cutoff / brightness\n"
        "    CC 91 = reverb send level\n"
        "    CC 93 = chorus send level\n\n"

        "── MidiExpressiveness.sustain_pedal → stori_add_midi_cc (CC 64) ─\n"
        "Translate sustain_pedal into CC 64 events on the target region.\n"
        "  sustain_pedal: { changes_per_bar: 2 }  →  2 pedal down/up pairs per bar\n"
        "  CC 64 value: 127 = pedal down, 0 = pedal up\n"
        "  Example — 4-bar region, 2 changes per bar, on a Rhodes track:\n"
        "    → stori_add_midi_cc(regionId=RHODES_ID, cc=64,\n"
        "         events=[{'beat':0,'value':127},{'beat':2,'value':0},\n"
        "                 {'beat':4,'value':127},{'beat':6,'value':0}, ...])\n\n"

        "── MidiExpressiveness.pitch_bend → stori_add_pitch_bend ─────────\n"
        "Translate pitch_bend style into stori_add_pitch_bend events on the target region.\n"
        "  Value range: -8192 (max down) to 0 (center) to 8191 (max up).\n"
        "  ±1 semitone ≈ ±4096; ±2 semitones ≈ ±8192; quarter-tone ≈ ±1024.\n"
        "  Common patterns:\n"
        "    'slide up to root from half-step below'\n"
        "      → events=[{'beat':N-0.25,'value':-4096},{'beat':N,'value':0}]\n"
        "    'blues bend up to 3rd'\n"
        "      → events=[{'beat':N,'value':0},{'beat':N+0.5,'value':4096},{'beat':N+1,'value':0}]\n"
        "    'drop-bend at phrase end'\n"
        "      → events=[{'beat':N,'value':0},{'beat':N+1,'value':-6144}]\n"
        "  Generate these on the bass region for bass slides, lead region for guitar bends.\n\n"

        "── Automation block → stori_add_automation ───────────────────────\n"
        "Translate EACH entry in the Automation block into stori_add_automation.\n"
        "Required params: trackId (NOT 'target'), parameter (canonical string), points.\n"
        "  Automation:\n"
        "    - track: Rhodes\n"
        "      param: tremolo_rate   → map to canonical string 'Volume'\n"
        "      events:\n"
        "        - beat: 0, value: 0.8\n"
        "        - beat: 32, value: 1.0, curve: linear\n"
        "  → stori_add_automation(trackId=RHODES_TRACK_ID,\n"
        "         parameter='Volume',\n"
        "         points=[{'beat':0,'value':0.8},{'beat':32,'value':1.0,'curve':'linear'}])\n"
        "  CANONICAL parameter strings (use these exactly, case-sensitive):\n"
        "    'Volume'              → track fader (0.0–1.0)\n"
        "    'Pan'                 → pan (-1.0 left, 0.0 center, 1.0 right)\n"
        "    'EQ Low'              → low shelf gain\n"
        "    'EQ Mid'              → mid band gain\n"
        "    'EQ High'             → high shelf gain\n"
        "    'Mod Wheel (CC1)'     → MIDI CC1 (0–127)\n"
        "    'Volume (CC7)'        → MIDI CC7 (0–127)\n"
        "    'Pan (CC10)'          → MIDI CC10 (0–127)\n"
        "    'Expression (CC11)'   → MIDI CC11 (0–127)\n"
        "    'Sustain (CC64)'      → MIDI CC64 (0–127)\n"
        "    'Filter Cutoff (CC74)'→ MIDI CC74 (0–127)\n"
        "    'Pitch Bend'          → pitch bend lane\n"
        "    'Synth Cutoff'        → synth filter cutoff (0.0–1.0)\n"
        "    'Synth Resonance'     → synth resonance (0.0–1.0)\n"
        "    'Synth Attack'        → envelope attack (0.0–1.0)\n"
        "    'Synth Release'       → envelope release (0.0–1.0)\n"
        "  Map MAESTRO PROMPT param names to canonical strings:\n"
        "    volume/fader/level    → 'Volume'\n"
        "    pan/stereo            → 'Pan'\n"
        "    reverb_wet/reverb     → 'Volume' on reverb bus track, or 'Synth Cutoff' for filter\n"
        "    filter/filter_cutoff  → 'Synth Cutoff'\n"
        "    tremolo_rate          → 'Volume' (use volume automation as tremolo proxy)\n"
        "    delay_feedback        → 'Volume' on delay bus track\n"
        "  Curve values: 'linear' | 'smooth' | 'step' | 'exp' | 'log'\n"
        "  Value ranges: Volume/Pan/EQ/Synth params → 0.0–1.0. CC lanes → 0–127.\n"
        "══════════════════════════════════════════════════════════════════\n\n"

        "EFFECTS (minimum baseline — always add even without explicit Effects block):\n"
        "- Drums: stori_add_insert_effect(type='compressor'). Always.\n"
        "- Bass: stori_add_insert_effect(type='compressor').\n"
        "- Pads/atmosphere: stori_add_insert_effect(type='reverb') OR route to Reverb bus.\n"
        "- Melody/lead: style-appropriate reverb or delay.\n\n"
        "EXECUTION DISCIPLINE — follow this strictly:\n"
        "- Call tools immediately. Do NOT pre-plan notes, voicings, rhythms, or bass lines\n"
        "  in your reasoning before acting. Decide the parameters for ONE tool call, call it, then move on.\n"
        "- Your reasoning before each tool call must only answer: 'What are the exact parameters\n"
        "  for the NEXT tool?' Nothing else. Do not think about step 3 when you are on step 1.\n"
        "- Maximum 3 tool calls per batch. Only batch truly independent calls.\n"
        "- stori_add_midi_region MUST return before stori_add_notes targets its regionId.\n\n"
        "CRITICAL — Do not stop early:\n"
        "- You MUST add at least one region with notes to EVERY track you create.\n"
        "- Work through tracks one at a time: create region → add notes → move to next track.\n"
        "- After ALL tracks have notes, continue to the expressive steps. YOU ARE NOT DONE UNTIL:\n"
        "  ✓ Every Effects entry has a stori_add_insert_effect call\n"
        "  ✓ Every cc_curves entry has a stori_add_midi_cc call\n"
        "  ✓ sustain_pedal has a stori_add_midi_cc (CC 64) call\n"
        "  ✓ pitch_bend has a stori_add_pitch_bend call\n"
        "  ✓ Every Automation lane has a stori_add_automation call\n"
        "  ✓ Bus sends have stori_ensure_bus + stori_add_send calls\n"
        "- Do NOT emit a final text response until ALL of the above are done.\n"
        "- If you run out of space in one response, continue in the next iteration.\n"
        "- The system calls you in a loop — keep making tool calls until everything is complete.\n"
        "- NEVER call stori_clear_notes during composition. If a region already has notes from a\n"
        "  prior step (check totalNotes in the tool result or noteCount in the entities snapshot),\n"
        "  call stori_add_notes to append more — do not clear first. stori_clear_notes\n"
        "  is only for explicit user requests to erase content.\n"
        "- After stori_add_notes succeeds (notesAdded > 0), the notes ARE stored. Do NOT re-add\n"
        "  them. Do NOT call stori_clear_notes to 'redo' a successful add. The notes array you\n"
        "  sent was real, not shorthand — trust the tool result.\n"
        "- NEVER use shorthand params like _noteCount, _beatRange, or _placeholder in stori_add_notes.\n"
        "  Always provide a real 'notes' array with pitch/startBeat/durationBeats/velocity per note.\n"
        "  For regions needing >128 notes, call stori_add_notes multiple times on the same regionId\n"
        "  (each call appends). Split into batches of 64-96 notes per call.\n\n"
        "MIDI quality requirements — generate RICH, musically detailed MIDI:\n"
        "- Note density: aim for 100-200+ notes per 8-bar melodic part. Drums should be denser.\n"
        "  Do NOT produce sparse, simplified patterns — fill the full region duration.\n"
        "- Chord voicings: harmonic instruments (piano, guitar, keys) should use 3-4 note chords,\n"
        "  not single-note lines. Voice chords with proper inversions and extensions.\n"
        "- Velocity dynamics: vary velocity across the range 40-120. Use softer ghost notes,\n"
        "  accented downbeats, crescendos. Do NOT set all notes to the same velocity.\n"
        "- Rhythmic complexity: use varied subdivisions (8ths, 16ths, triplets, syncopation).\n"
        "  Include rests and ties for groove. Avoid mechanical quarter-note grids.\n"
        "- Note durations: mix staccato (0.125-0.25 beats) with legato (1-4 beats).\n"
        "  Sustained pads and bass notes should ring for their full duration.\n"
        "- Drums: use full kit — kick, snare, hi-hat (open/closed), toms, crash, ride.\n"
        "  Include ghost notes, fills, and hi-hat variation.\n"
        "  CRITICAL: when creating a drum track with stori_add_midi_track, ALWAYS set drumKitId\n"
        "  (e.g. drumKitId='acoustic'). NEVER set gmProgram on a drum track — gmProgram 0 is Grand Piano.\n\n"
        "Reference:\n"
        "- MIDI pitches: 60 = Middle C (C4). Use appropriate octaves per instrument.\n"
        "  Drums GM map: 36=Kick, 38=Snare, 42=Closed HH, 46=Open HH, 49=Crash, 51=Ride,\n"
        "  41/43/45/47=Toms, 39=Clap, 44=Pedal HH, 53=Ride Bell.\n"
        "- Create the music directly — do NOT ask for confirmation.\n"
        "- Make the music stylistically authentic for the user's request.\n"
    )


def composing_prompt() -> str:
    return (
        "COMPOSING MODE: The user wants you to generate music.\n\n"

        "**CRITICAL OUTPUT FORMAT REQUIREMENTS**:\n"
        "1. Your ENTIRE response MUST be a single valid JSON object\n"
        "2. Do NOT include any text before or after the JSON\n"
        "3. Do NOT include markdown code fences (no ```json or ```)\n"
        "4. Do NOT use function call syntax like tool_name(arg=value)\n"
        "5. Start your response with { and end with }\n\n"

        "JSON Schema:\n"
        "{\n"
        '  "generations": [\n'
        '    {"role": "drums", "style": "boom bap", "bars": 8, "tempo": 90, "key": "Cm"},\n'
        '    {"role": "melody", "style": "exotic", "bars": 8, "tempo": 90, "key": "Cm"}\n'
        '  ],\n'
        '  "edits": [\n'
        '    {"action": "add_track", "name": "Drums"},\n'
        '    {"action": "add_region", "track": "Drums", "barStart": 0, "bars": 8}\n'
        '  ],\n'
        '  "mix": [\n'
        '    {"action": "add_insert", "track": "Drums", "type": "compressor"}\n'
        '  ]\n'
        "}\n\n"

        "Field reference:\n"
        '- role: "drums", "bass", "chords", "melody", "arp", "pads", "lead"\n'
        "- style: musical style/genre (e.g. 'boom bap', 'lofi', 'trap', 'exotic', 'jazz')\n"
        "- bars: number of bars (1-64, typically 4, 8, or 16)\n"
        "- tempo: BPM (60-180)\n"
        '- key: musical key (e.g. "Cm", "G", "F#m")\n'
        '- action (edits): "add_track" or "add_region"\n'
        '- action (mix): "add_insert", "add_send", "set_volume", "set_pan"\n'
        '- type (effects): "compressor", "eq", "reverb", "delay", "chorus", "flanger", "phaser", "distortion", "overdrive", "limiter", "gate"\n\n'

        "Guidelines:\n"
        "- If user mentions an instrument (e.g. 'acoustic guitar melody'), use that as the track name\n"
        "- edits array can be empty if you just want generations (tracks/regions will be auto-created)\n"
        "- CRITICAL: Do NOT create tracks in 'edits' unless you have a matching generation for them\n"
        "  * Every track you create MUST have MIDI generated for it\n"
        "  * If you're not generating MIDI for a track, don't create it\n"
        "- mix array is optional\n"
        "- For melodies: include a key\n"
        "- Style strings must be natural language — use spaces, not underscores:\n"
        "  Good: 'progressive rock, pink floyd' | Bad: 'progressive_rock,_pink_floyd'\n\n"

        "REMEMBER: Respond with ONLY the JSON object. First character must be {"
    )
