"""add_musehub_pr_comments

Revision ID: 23c0aad0f741
Revises: 0001
Create Date: 2026-02-28 21:37:04.878701+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23c0aad0f741'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musehub_render_jobs',
    sa.Column('render_job_id', sa.String(length=36), nullable=False),
    sa.Column('repo_id', sa.String(length=36), nullable=False),
    sa.Column('commit_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('midi_count', sa.Integer(), nullable=False),
    sa.Column('mp3_object_ids', sa.JSON(), nullable=False),
    sa.Column('image_object_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['musehub_repos.repo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('render_job_id'),
    sa.UniqueConstraint('repo_id', 'commit_id', name='uq_musehub_render_jobs_repo_commit')
    )
    op.create_index(op.f('ix_musehub_render_jobs_commit_id'), 'musehub_render_jobs', ['commit_id'], unique=False)
    op.create_index(op.f('ix_musehub_render_jobs_repo_id'), 'musehub_render_jobs', ['repo_id'], unique=False)
    op.create_index(op.f('ix_musehub_render_jobs_status'), 'musehub_render_jobs', ['status'], unique=False)
    op.alter_column('access_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('access_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_messages', 'tokens_used',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('conversation_messages', 'cost_cents',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_messages', 'tool_calls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('conversation_messages', 'sse_events',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('conversation_messages', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('conversation_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'project_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('message_actions', 'extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('message_actions', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_comments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_musehub_comments_target'), table_name='musehub_comments')
    op.create_index(op.f('ix_musehub_comments_created_at'), 'musehub_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_musehub_comments_target_id'), 'musehub_comments', ['target_id'], unique=False)
    op.create_index(op.f('ix_musehub_comments_target_type'), 'musehub_comments', ['target_type'], unique=False)
    op.alter_column('musehub_commits', 'parent_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_commits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_download_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_musehub_download_events_created_at'), 'musehub_download_events', ['created_at'], unique=False)
    op.alter_column('musehub_follows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_forks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_musehub_forks_fork_repo_id'), 'musehub_forks', ['fork_repo_id'], unique=False)
    op.alter_column('musehub_issues', 'body',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_issues', 'state',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_issues', 'labels',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_issues', 'author',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_notifications', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_musehub_notifications_created_at'), 'musehub_notifications', ['created_at'], unique=False)
    op.alter_column('musehub_objects', 'size_bytes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_objects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_profiles', 'pinned_repo_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_pull_requests', 'body',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_pull_requests', 'state',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_pull_requests', 'author',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_pull_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_reactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_musehub_reactions_target'), table_name='musehub_reactions')
    op.create_index(op.f('ix_musehub_reactions_repo_id'), 'musehub_reactions', ['repo_id'], unique=False)
    op.create_index(op.f('ix_musehub_reactions_target_id'), 'musehub_reactions', ['target_id'], unique=False)
    op.create_index(op.f('ix_musehub_reactions_target_type'), 'musehub_reactions', ['target_type'], unique=False)
    op.create_index(op.f('ix_musehub_reactions_user_id'), 'musehub_reactions', ['user_id'], unique=False)
    op.alter_column('musehub_releases', 'body',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_releases', 'download_urls',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_releases', 'author',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_releases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_repos', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_repos', 'description',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_repos', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_repos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_musehub_repos_visibility'), table_name='musehub_repos')
    op.alter_column('musehub_sessions', 'schema_version',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'participants',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'location',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'intent',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'commits',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'notes',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_stars', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_view_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_watches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_webhook_deliveries', 'attempt',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_webhook_deliveries', 'success',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_webhook_deliveries', 'response_status',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_webhook_deliveries', 'response_body',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_webhook_deliveries', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_webhooks', 'events',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_webhooks', 'secret',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_webhooks', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('musehub_webhooks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usage_logs', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usage_logs', 'completion_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usage_logs', 'cost_cents',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usage_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'budget_cents',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'budget_limit_cents',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('variations', 'conversation_id',
               existing_type=sa.VARCHAR(length=36),
               server_default=None,
               existing_nullable=False)
    op.alter_column('variations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('variations', 'beat_range_start',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('variations', 'beat_range_end',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('variations', 'is_head',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('variations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('variations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_variations_status'), table_name='variations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_variations_status'), 'variations', ['status'], unique=False)
    op.alter_column('variations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('variations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('variations', 'is_head',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('variations', 'beat_range_end',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('variations', 'beat_range_start',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('variations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'created'::character varying"),
               existing_nullable=False)
    op.alter_column('variations', 'conversation_id',
               existing_type=sa.VARCHAR(length=36),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('users', 'budget_limit_cents',
               existing_type=sa.INTEGER(),
               server_default=sa.text('500'),
               existing_nullable=False)
    op.alter_column('users', 'budget_cents',
               existing_type=sa.INTEGER(),
               server_default=sa.text('500'),
               existing_nullable=False)
    op.alter_column('usage_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('usage_logs', 'cost_cents',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('usage_logs', 'completion_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('usage_logs', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('musehub_webhooks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_webhooks', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('musehub_webhooks', 'secret',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('musehub_webhooks', 'events',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
    op.alter_column('musehub_webhook_deliveries', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_webhook_deliveries', 'response_body',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('musehub_webhook_deliveries', 'response_status',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('musehub_webhook_deliveries', 'success',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('musehub_webhook_deliveries', 'attempt',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('musehub_watches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_view_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_stars', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'notes',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'commits',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'intent',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'location',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'participants',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
    op.alter_column('musehub_sessions', 'schema_version',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'1'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('ix_musehub_repos_visibility'), 'musehub_repos', ['visibility'], unique=False)
    op.alter_column('musehub_repos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_repos', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
    op.alter_column('musehub_repos', 'description',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('musehub_repos', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'private'::character varying"),
               existing_nullable=False)
    op.alter_column('musehub_releases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_releases', 'author',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('musehub_releases', 'download_urls',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=False)
    op.alter_column('musehub_releases', 'body',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.drop_index(op.f('ix_musehub_reactions_user_id'), table_name='musehub_reactions')
    op.drop_index(op.f('ix_musehub_reactions_target_type'), table_name='musehub_reactions')
    op.drop_index(op.f('ix_musehub_reactions_target_id'), table_name='musehub_reactions')
    op.drop_index(op.f('ix_musehub_reactions_repo_id'), table_name='musehub_reactions')
    op.create_index(op.f('ix_musehub_reactions_target'), 'musehub_reactions', ['target_type', 'target_id'], unique=False)
    op.alter_column('musehub_reactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_pull_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_pull_requests', 'author',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('musehub_pull_requests', 'state',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=False)
    op.alter_column('musehub_pull_requests', 'body',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('musehub_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_profiles', 'pinned_repo_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
    op.alter_column('musehub_objects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_objects', 'size_bytes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_musehub_notifications_created_at'), table_name='musehub_notifications')
    op.alter_column('musehub_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('musehub_notifications', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=False)
    op.alter_column('musehub_issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_issues', 'author',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('musehub_issues', 'labels',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
    op.alter_column('musehub_issues', 'state',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=False)
    op.alter_column('musehub_issues', 'body',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.drop_index(op.f('ix_musehub_forks_fork_repo_id'), table_name='musehub_forks')
    op.alter_column('musehub_forks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_follows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_musehub_download_events_created_at'), table_name='musehub_download_events')
    op.alter_column('musehub_download_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_commits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_commits', 'parent_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
    op.drop_index(op.f('ix_musehub_comments_target_type'), table_name='musehub_comments')
    op.drop_index(op.f('ix_musehub_comments_target_id'), table_name='musehub_comments')
    op.drop_index(op.f('ix_musehub_comments_created_at'), table_name='musehub_comments')
    op.create_index(op.f('ix_musehub_comments_target'), 'musehub_comments', ['target_type', 'target_id'], unique=False)
    op.alter_column('musehub_comments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('musehub_comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('musehub_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('message_actions', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('message_actions', 'extra_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('conversations', 'project_context',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('conversations', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("'New Conversation'::character varying"),
               existing_nullable=False)
    op.alter_column('conversation_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('conversation_messages', 'extra_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('conversation_messages', 'sse_events',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('conversation_messages', 'tool_calls',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('conversation_messages', 'cost_cents',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('conversation_messages', 'tokens_used',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('access_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('access_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_musehub_render_jobs_status'), table_name='musehub_render_jobs')
    op.drop_index(op.f('ix_musehub_render_jobs_repo_id'), table_name='musehub_render_jobs')
    op.drop_index(op.f('ix_musehub_render_jobs_commit_id'), table_name='musehub_render_jobs')
    op.drop_table('musehub_render_jobs')
    # ### end Alembic commands ###
