"""MuseHub sample-data seed script.

Inserts two users, three repos, realistic commit histories, branches,
issues, PRs, releases, sessions, and stars directly into Postgres so
every implemented UI URL renders real data.

Run inside the container:
  docker compose exec maestro python3 /app/scripts/seed_musehub.py

Idempotent: all IDs are deterministic constants, and the script skips
if data already exists. Use --force to wipe and re-insert.

To add data for a future URL, append rows to the relevant section in
seed() and add the URL to the print block at the bottom.
"""
from __future__ import annotations

import asyncio
import hashlib
import sys
from datetime import datetime, timedelta, timezone

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

from maestro.config import settings
from maestro.db.musehub_models import (
    MusehubBranch,
    MusehubCommit,
    MusehubIssue,
    MusehubProfile,
    MusehubPullRequest,
    MusehubRelease,
    MusehubRepo,
    MusehubSession,
    MusehubStar,
)


# ---------------------------------------------------------------------------
# Deterministic constants — IDs never change between runs so URLs are stable
# ---------------------------------------------------------------------------

GABRIEL_ID = "user-gabriel-001"
SOFIA_ID = "user-sofia-002"

REPO_NEO_SOUL = "repo-neo-soul-00000001"
REPO_MODAL_JAZZ = "repo-modal-jazz-000001"
REPO_AMBIENT = "repo-ambient-textures-1"

PR_HORN = "pr-horn-section-0000001"
PR_PHRYGIAN = "pr-phrygian-bridge-0001"
PR_DRUMS = "pr-drum-humanize-00001"

SESS_STUDIO = "sess-studio-a-0000001"
SESS_HOME = "sess-home-studio-00001"
SESS_REMOTE = "sess-remote-collab-001"


def _now(delta_days: int = 0, delta_hours: int = 0) -> datetime:
    return datetime.now(tz=timezone.utc) - timedelta(days=delta_days, hours=delta_hours)


def _sha(seed: str) -> str:
    """Deterministic 64-char hex digest — stable commit IDs across runs."""
    return hashlib.sha256(seed.encode()).hexdigest()


# ---------------------------------------------------------------------------
# Seed
# ---------------------------------------------------------------------------


async def seed(db: AsyncSession, force: bool = False) -> None:
    print("🌱 Seeding MuseHub sample data…")

    result = await db.execute(text("SELECT COUNT(*) FROM musehub_repos"))
    existing = result.scalar() or 0
    if existing > 0 and not force:
        print(f"  ⚠️  {existing} repo(s) already exist — skipping. Pass --force to wipe and reseed.")
        _print_urls()
        return

    if existing > 0 and force:
        print("  🗑  --force: clearing existing seed data…")
        for tbl in [
            "musehub_stars", "musehub_sessions", "musehub_releases",
            "musehub_webhook_deliveries", "musehub_webhooks",
            "musehub_pull_requests", "musehub_issues", "musehub_branches",
            "musehub_commits", "musehub_objects", "musehub_repos",
            "musehub_profiles",
        ]:
            await db.execute(text(f"DELETE FROM {tbl}"))

    # -----------------------------------------------------------------------
    # 1. User profiles
    # -----------------------------------------------------------------------
    db.add(MusehubProfile(
        user_id=GABRIEL_ID,
        username="gabriel",
        bio="Composer & producer. Neo-soul, modal jazz, ambient textures. All sounds generated by Stori.",
        avatar_url="https://api.dicebear.com/7.x/avataaars/svg?seed=gabriel",
        pinned_repo_ids=[REPO_NEO_SOUL, REPO_MODAL_JAZZ],
    ))
    db.add(MusehubProfile(
        user_id=SOFIA_ID,
        username="sofia",
        bio="Classical-meets-electronic. Exploring algorithmic composition with Stori Maestro.",
        avatar_url="https://api.dicebear.com/7.x/avataaars/svg?seed=sofia",
        pinned_repo_ids=[REPO_AMBIENT],
    ))
    print("  ✅ Profiles: gabriel, sofia")

    # -----------------------------------------------------------------------
    # 2. Repos
    # -----------------------------------------------------------------------
    db.add(MusehubRepo(
        repo_id=REPO_NEO_SOUL,
        name="Neo-Soul Experiment",
        owner="gabriel",
        slug="neo-soul-experiment",
        visibility="public",
        owner_user_id=GABRIEL_ID,
        description="A funk-influenced neo-soul project exploring polyrhythmic grooves in F# minor.",
        tags=["neo-soul", "funk", "F# minor", "polyrhythm", "bass-heavy"],
        key_signature="F# minor",
        tempo_bpm=92,
        created_at=_now(delta_days=30),
    ))
    db.add(MusehubRepo(
        repo_id=REPO_MODAL_JAZZ,
        name="Modal Jazz Sketches",
        owner="gabriel",
        slug="modal-jazz-sketches",
        visibility="public",
        owner_user_id=GABRIEL_ID,
        description="Exploring Dorian and Phrygian modes. Miles Davis and Coltrane are the north stars.",
        tags=["jazz", "modal", "Dorian", "Phrygian", "piano", "trumpet"],
        key_signature="D Dorian",
        tempo_bpm=120,
        created_at=_now(delta_days=14),
    ))
    db.add(MusehubRepo(
        repo_id=REPO_AMBIENT,
        name="Ambient Textures Vol. 1",
        owner="sofia",
        slug="ambient-textures-vol-1",
        visibility="public",
        owner_user_id=SOFIA_ID,
        description="Slow-evolving pads and generative arpeggios. Inspired by Eno and Nils Frahm.",
        tags=["ambient", "generative", "pads", "Eb major", "slow"],
        key_signature="Eb major",
        tempo_bpm=60,
        created_at=_now(delta_days=7),
    ))
    print("  ✅ Repos: neo-soul-experiment, modal-jazz-sketches, ambient-textures-vol-1")

    # -----------------------------------------------------------------------
    # 3. Commits — Neo-Soul Experiment
    # -----------------------------------------------------------------------
    ns_c1 = _sha("neo-soul-commit-1")
    ns_c2 = _sha("neo-soul-commit-2")
    ns_c3 = _sha("neo-soul-commit-3")
    ns_c4 = _sha("neo-soul-commit-4")
    ns_c5 = _sha("neo-soul-commit-5")
    ns_c6 = _sha("neo-soul-commit-6-feat")

    for c in [
        MusehubCommit(commit_id=ns_c1, repo_id=REPO_NEO_SOUL, branch="main",
                      parent_ids=[], message="init: establish F# minor groove template at 92 BPM",
                      author="gabriel", timestamp=_now(delta_days=28), snapshot_id=_sha("snap-ns-1")),
        MusehubCommit(commit_id=ns_c2, repo_id=REPO_NEO_SOUL, branch="main",
                      parent_ids=[ns_c1], message="feat(bass): add polyrhythmic bass line — 3-against-4 pulse",
                      author="gabriel", timestamp=_now(delta_days=21), snapshot_id=_sha("snap-ns-2")),
        MusehubCommit(commit_id=ns_c3, repo_id=REPO_NEO_SOUL, branch="main",
                      parent_ids=[ns_c2], message="feat(keys): Rhodes chord voicings with upper-structure triads",
                      author="gabriel", timestamp=_now(delta_days=14), snapshot_id=_sha("snap-ns-3")),
        MusehubCommit(commit_id=ns_c4, repo_id=REPO_NEO_SOUL, branch="main",
                      parent_ids=[ns_c3], message="refactor(drums): humanize ghost notes, tighten hi-hat velocity",
                      author="gabriel", timestamp=_now(delta_days=7), snapshot_id=_sha("snap-ns-4")),
        MusehubCommit(commit_id=ns_c5, repo_id=REPO_NEO_SOUL, branch="main",
                      parent_ids=[ns_c4], message="feat(strings): bridge string section — section:bridge track:strings",
                      author="gabriel", timestamp=_now(delta_days=2), snapshot_id=_sha("snap-ns-5")),
        MusehubCommit(commit_id=ns_c6, repo_id=REPO_NEO_SOUL, branch="feat/horn-section",
                      parent_ids=[ns_c3], message="feat(horns): sketch trumpet + alto sax counter-melody",
                      author="gabriel", timestamp=_now(delta_days=5), snapshot_id=_sha("snap-ns-6")),
    ]:
        db.add(c)

    db.add(MusehubBranch(repo_id=REPO_NEO_SOUL, name="main", head_commit_id=ns_c5))
    db.add(MusehubBranch(repo_id=REPO_NEO_SOUL, name="feat/horn-section", head_commit_id=ns_c6))

    # -----------------------------------------------------------------------
    # 4. Commits — Modal Jazz Sketches
    # -----------------------------------------------------------------------
    mj_c1 = _sha("modal-jazz-commit-1")
    mj_c2 = _sha("modal-jazz-commit-2")
    mj_c3 = _sha("modal-jazz-commit-3")
    mj_c4 = _sha("modal-jazz-commit-4-bridge")

    for c in [
        MusehubCommit(commit_id=mj_c1, repo_id=REPO_MODAL_JAZZ, branch="main",
                      parent_ids=[], message="init: D Dorian vamp at 120 BPM — piano + bass",
                      author="gabriel", timestamp=_now(delta_days=12), snapshot_id=_sha("snap-mj-1")),
        MusehubCommit(commit_id=mj_c2, repo_id=REPO_MODAL_JAZZ, branch="main",
                      parent_ids=[mj_c1], message="feat(melody): Coltrane-inspired pentatonic runs over the IV chord",
                      author="gabriel", timestamp=_now(delta_days=9), snapshot_id=_sha("snap-mj-2")),
        MusehubCommit(commit_id=mj_c3, repo_id=REPO_MODAL_JAZZ, branch="main",
                      parent_ids=[mj_c2], message="feat(drums): brush kit — swing factor 0.65",
                      author="gabriel", timestamp=_now(delta_days=5), snapshot_id=_sha("snap-mj-3")),
        MusehubCommit(commit_id=mj_c4, repo_id=REPO_MODAL_JAZZ, branch="experiment/phrygian-bridge",
                      parent_ids=[mj_c2], message="experiment: Phrygian dominant bridge — E Phrygian Dominant",
                      author="gabriel", timestamp=_now(delta_days=3), snapshot_id=_sha("snap-mj-4")),
    ]:
        db.add(c)

    db.add(MusehubBranch(repo_id=REPO_MODAL_JAZZ, name="main", head_commit_id=mj_c3))
    db.add(MusehubBranch(repo_id=REPO_MODAL_JAZZ, name="experiment/phrygian-bridge", head_commit_id=mj_c4))

    # -----------------------------------------------------------------------
    # 5. Commits — Ambient Textures (sofia)
    # -----------------------------------------------------------------------
    amb_c1 = _sha("ambient-commit-1")
    amb_c2 = _sha("ambient-commit-2")
    amb_c3 = _sha("ambient-commit-3")

    for c in [
        MusehubCommit(commit_id=amb_c1, repo_id=REPO_AMBIENT, branch="main",
                      parent_ids=[], message="init: Eb major pad foundation — slow attack 4s release 8s",
                      author="sofia", timestamp=_now(delta_days=6), snapshot_id=_sha("snap-amb-1")),
        MusehubCommit(commit_id=amb_c2, repo_id=REPO_AMBIENT, branch="main",
                      parent_ids=[amb_c1], message="feat(arp): generative 16th-note arpeggiator — random seed 42",
                      author="sofia", timestamp=_now(delta_days=4), snapshot_id=_sha("snap-amb-2")),
        MusehubCommit(commit_id=amb_c3, repo_id=REPO_AMBIENT, branch="main",
                      parent_ids=[amb_c2], message="feat(texture): granular string texture layer — section:intro",
                      author="sofia", timestamp=_now(delta_days=1), snapshot_id=_sha("snap-amb-3")),
    ]:
        db.add(c)

    db.add(MusehubBranch(repo_id=REPO_AMBIENT, name="main", head_commit_id=amb_c3))
    print("  ✅ Commits & branches seeded")

    # -----------------------------------------------------------------------
    # 6. Issues
    # -----------------------------------------------------------------------
    for issue in [
        MusehubIssue(repo_id=REPO_NEO_SOUL, number=1, state="open",
                     title="Bass line loses rhythmic tension in bar 9",
                     body="The 3-against-4 pulse drifts in bar 9. Groove score drops from 0.87 to 0.71. Consider adding a ghost note on beat 2.5.",
                     labels=["groove", "bass"], created_at=_now(delta_days=18)),
        MusehubIssue(repo_id=REPO_NEO_SOUL, number=2, state="open",
                     title="Add guitar scratch rhythm track",
                     body="The arrangement feels sparse without a scratch guitar. Should sit in the upper mid-range to complement the Rhodes voicings.",
                     labels=["arrangement", "enhancement"], created_at=_now(delta_days=10)),
        MusehubIssue(repo_id=REPO_NEO_SOUL, number=3, state="closed",
                     title="Tempo fluctuates between bars 4 and 8",
                     body="Resolved by re-quantizing with --tight humanization and fixing the drum anchor.",
                     labels=["tempo", "drums"], created_at=_now(delta_days=20)),
        MusehubIssue(repo_id=REPO_MODAL_JAZZ, number=1, state="open",
                     title="Phrygian bridge feels too abrupt — needs a ii-V turnaround",
                     body="The jump from D Dorian to E Phrygian Dominant needs a 2-bar turnaround. Suggest Am7b5 → D7alt → E Phrygian.",
                     labels=["harmony", "bridge"], created_at=_now(delta_days=3)),
        MusehubIssue(repo_id=REPO_MODAL_JAZZ, number=2, state="open",
                     title="Swing factor inconsistent between piano and bass",
                     body="Piano is at 0.65 swing but bass is tighter (0.55). Should match for groove cohesion.",
                     labels=["groove", "timing"], created_at=_now(delta_days=1)),
        MusehubIssue(repo_id=REPO_AMBIENT, number=1, state="open",
                     title="Arpeggiator repeats same pattern — needs more variation",
                     body="After 32 bars the generative arp becomes predictable. Consider modulating the random seed every 8 bars.",
                     labels=["generative", "variety"], created_at=_now(delta_hours=12)),
    ]:
        db.add(issue)
    print("  ✅ Issues seeded")

    # -----------------------------------------------------------------------
    # 7. Pull Requests
    # -----------------------------------------------------------------------
    for pr in [
        MusehubPullRequest(
            pr_id=PR_HORN, repo_id=REPO_NEO_SOUL,
            title="Add horn section counter-melody",
            body="Brings in trumpet + alto sax sketch from `feat/horn-section`.\n\n## Changes\n- `tracks/trumpet.mid` — 8-bar counter-melody\n- `tracks/alto_sax.mid` — response phrase\n\n## Analysis\n- Harmonic tension increases by +0.12 in chorus\n- Contour: arch shape over 4 bars",
            state="open", from_branch="feat/horn-section", to_branch="main",
            created_at=_now(delta_days=4)),
        MusehubPullRequest(
            pr_id=PR_PHRYGIAN, repo_id=REPO_MODAL_JAZZ,
            title="Phrygian dominant bridge experiment → main",
            body="Merging the E Phrygian Dominant bridge after adding the ii-V turnaround. Groove score stays above 0.80 throughout.",
            state="open", from_branch="experiment/phrygian-bridge", to_branch="main",
            created_at=_now(delta_days=2)),
        MusehubPullRequest(
            pr_id=PR_DRUMS, repo_id=REPO_NEO_SOUL,
            title="Humanize drum ghost notes",
            body="Applied `muse humanize --natural --track=drums`. Groove score improved from 0.71 to 0.89.",
            state="merged", from_branch="fix/drum-humanization", to_branch="main",
            merge_commit_id=ns_c4, created_at=_now(delta_days=8)),
    ]:
        db.add(pr)
    print("  ✅ Pull requests seeded")

    # -----------------------------------------------------------------------
    # 8. Releases
    # -----------------------------------------------------------------------
    for release in [
        MusehubRelease(
            repo_id=REPO_NEO_SOUL, tag="v0.1.0", title="Groove Foundation",
            body="## v0.1.0 — Groove Foundation\n\nFirst releasable state. Bass, Rhodes, and drums are locked in.\n\n### What's included\n- `tracks/bass.mid`\n- `tracks/rhodes.mid`\n- `tracks/drums.mid`\n\n### Listen\nBPM: 92 | Key: F# minor | Swing: 0.55",
            commit_id=ns_c4,
            download_urls={"midi_bundle": "/releases/neo-soul-v0.1.0.zip", "mp3": "/releases/neo-soul-v0.1.0.mp3"},
            created_at=_now(delta_days=6)),
        MusehubRelease(
            repo_id=REPO_AMBIENT, tag="v1.0.0", title="Ambient Textures Vol. 1 — Full Release",
            body="## v1.0.0\n\nComplete ambient suite. Three layers — pad, generative arpeggiator, and granular strings.\n\n### Mood\nMeditative, spacious, slowly evolving.\n\n### Technical\nBPM: 60 | Key: Eb major | Duration: ~12 minutes",
            commit_id=amb_c3,
            download_urls={"midi_bundle": "/releases/ambient-vol1.zip", "stems": "/releases/ambient-vol1-stems.zip", "mp3": "/releases/ambient-vol1.mp3"},
            created_at=_now(delta_days=1)),
    ]:
        db.add(release)
    print("  ✅ Releases seeded")

    # -----------------------------------------------------------------------
    # 9. Sessions
    # -----------------------------------------------------------------------
    for session in [
        MusehubSession(
            session_id=SESS_STUDIO, repo_id=REPO_NEO_SOUL,
            started_at=_now(delta_days=21), ended_at=_now(delta_days=21, delta_hours=-3),
            participants=["gabriel", "marcus"], location="Studio A, São Paulo",
            intent="Lock in the polyrhythmic bass line and establish the harmonic framework",
            commits=[ns_c2, ns_c3],
            notes="Marcus played Rhodes live — captured MIDI via USB. Bass took 6 takes to nail the 3-against-4.",
            is_active=False, created_at=_now(delta_days=21)),
        MusehubSession(
            session_id=SESS_HOME, repo_id=REPO_NEO_SOUL,
            started_at=_now(delta_days=7), ended_at=_now(delta_days=7, delta_hours=-2),
            participants=["gabriel"], location="Home studio",
            intent="Humanize drums, add string section for bridge",
            commits=[ns_c4, ns_c5],
            notes="Used --natural humanization preset. String voicings reference Quincy Jones arranging style.",
            is_active=False, created_at=_now(delta_days=7)),
        MusehubSession(
            session_id=SESS_REMOTE, repo_id=REPO_AMBIENT,
            started_at=_now(delta_days=4), ended_at=_now(delta_days=4, delta_hours=-4),
            participants=["sofia", "yuki"], location="Remote (Sofia: Lisbon, Yuki: Tokyo)",
            intent="Build generative arpeggiator and granular texture layer",
            commits=[amb_c2, amb_c3],
            notes="Yuki contributed the granular string algorithm. Random seed 42 gives the most organic result.",
            is_active=False, created_at=_now(delta_days=4)),
    ]:
        db.add(session)
    print("  ✅ Sessions seeded")

    # -----------------------------------------------------------------------
    # 10. Stars
    # -----------------------------------------------------------------------
    db.add(MusehubStar(repo_id=REPO_NEO_SOUL, user_id=SOFIA_ID, created_at=_now(delta_days=5)))
    db.add(MusehubStar(repo_id=REPO_AMBIENT, user_id=GABRIEL_ID, created_at=_now(delta_days=2)))
    db.add(MusehubStar(repo_id=REPO_MODAL_JAZZ, user_id=SOFIA_ID, created_at=_now(delta_days=1)))
    print("  ✅ Stars seeded")

    await db.commit()
    _print_urls()


def _print_urls() -> None:
    BASE = "http://localhost:10001/musehub/ui"
    ns_c2 = _sha("neo-soul-commit-2")
    ns_c5 = _sha("neo-soul-commit-5")
    mj_c3 = _sha("modal-jazz-commit-3")
    amb_c3 = _sha("ambient-commit-3")

    print()
    print("=" * 70)
    print("🎵 MUSEHUB URLs — localhost:10001")
    print("=" * 70)

    print("\n── Repo landing pages ──────────────────────────────────────")
    print(f"  {BASE}/gabriel/neo-soul-experiment")
    print(f"  {BASE}/gabriel/modal-jazz-sketches")
    print(f"  {BASE}/sofia/ambient-textures-vol-1")

    print("\n── Commit detail ───────────────────────────────────────────")
    print(f"  {BASE}/gabriel/neo-soul-experiment/commits/{ns_c5[:8]}")
    print(f"  {BASE}/gabriel/neo-soul-experiment/commits/{ns_c2[:8]}")
    print(f"  {BASE}/gabriel/modal-jazz-sketches/commits/{mj_c3[:8]}")
    print(f"  {BASE}/sofia/ambient-textures-vol-1/commits/{amb_c3[:8]}")

    print("\n── DAG commit graph ────────────────────────────────────────")
    print(f"  {BASE}/gabriel/neo-soul-experiment/graph")
    print(f"  {BASE}/gabriel/modal-jazz-sketches/graph")

    print("\n── Issues ──────────────────────────────────────────────────")
    print(f"  {BASE}/gabriel/neo-soul-experiment/issues")
    print(f"  {BASE}/gabriel/neo-soul-experiment/issues/1")
    print(f"  {BASE}/gabriel/neo-soul-experiment/issues/2")
    print(f"  {BASE}/gabriel/neo-soul-experiment/issues/3")
    print(f"  {BASE}/gabriel/modal-jazz-sketches/issues")
    print(f"  {BASE}/gabriel/modal-jazz-sketches/issues/1")
    print(f"  {BASE}/sofia/ambient-textures-vol-1/issues")
    print(f"  {BASE}/sofia/ambient-textures-vol-1/issues/1")

    print("\n── Pull Requests ───────────────────────────────────────────")
    print(f"  {BASE}/gabriel/neo-soul-experiment/pulls")
    print(f"  {BASE}/gabriel/neo-soul-experiment/pulls/{PR_HORN}")
    print(f"  {BASE}/gabriel/neo-soul-experiment/pulls/{PR_DRUMS}")
    print(f"  {BASE}/gabriel/modal-jazz-sketches/pulls")
    print(f"  {BASE}/gabriel/modal-jazz-sketches/pulls/{PR_PHRYGIAN}")

    print("\n── Releases ────────────────────────────────────────────────")
    print(f"  {BASE}/gabriel/neo-soul-experiment/releases")
    print(f"  {BASE}/gabriel/neo-soul-experiment/releases/v0.1.0")
    print(f"  {BASE}/sofia/ambient-textures-vol-1/releases")
    print(f"  {BASE}/sofia/ambient-textures-vol-1/releases/v1.0.0")

    print("\n── Recording sessions ──────────────────────────────────────")
    print(f"  {BASE}/gabriel/neo-soul-experiment/sessions")
    print(f"  {BASE}/gabriel/neo-soul-experiment/sessions/{SESS_STUDIO}")
    print(f"  {BASE}/gabriel/neo-soul-experiment/sessions/{SESS_HOME}")
    print(f"  {BASE}/sofia/ambient-textures-vol-1/sessions")
    print(f"  {BASE}/sofia/ambient-textures-vol-1/sessions/{SESS_REMOTE}")

    print("\n── Timeline ────────────────────────────────────────────────")
    print(f"  {BASE}/gabriel/neo-soul-experiment/timeline")
    print(f"  {BASE}/gabriel/modal-jazz-sketches/timeline")
    print(f"  {BASE}/sofia/ambient-textures-vol-1/timeline")

    print("\n── Divergence radar ────────────────────────────────────────")
    print(f"  {BASE}/gabriel/neo-soul-experiment/divergence")
    print(f"  {BASE}/gabriel/modal-jazz-sketches/divergence")

    print("\n── AI context viewer ───────────────────────────────────────")
    print(f"  {BASE}/gabriel/neo-soul-experiment/context/main")
    print(f"  {BASE}/gabriel/modal-jazz-sketches/context/main")
    print(f"  {BASE}/sofia/ambient-textures-vol-1/context/main")

    print("\n── Credits / liner notes ───────────────────────────────────")
    print(f"  {BASE}/gabriel/neo-soul-experiment/credits")
    print(f"  {BASE}/sofia/ambient-textures-vol-1/credits")

    print("\n── Embeddable audio player ─────────────────────────────────")
    print(f"  {BASE}/gabriel/neo-soul-experiment/embed/main")
    print(f"  {BASE}/sofia/ambient-textures-vol-1/embed/main")

    print("\n── In-repo search ──────────────────────────────────────────")
    print(f"  {BASE}/gabriel/neo-soul-experiment/search")
    print(f"  {BASE}/gabriel/modal-jazz-sketches/search")

    print("\n── Musical analysis pages ──────────────────────────────────")
    print(f"  {BASE}/gabriel/neo-soul-experiment/analysis/main/contour")
    print(f"  {BASE}/gabriel/neo-soul-experiment/analysis/main/dynamics")
    print(f"  {BASE}/gabriel/neo-soul-experiment/analysis/main/tempo")
    print(f"  {BASE}/gabriel/modal-jazz-sketches/analysis/main/contour")
    print(f"  {BASE}/sofia/ambient-textures-vol-1/analysis/main/dynamics")

    print()
    print("=" * 70)
    print("✅ Done.")
    print("=" * 70)


async def main() -> None:
    force = "--force" in sys.argv
    engine = create_async_engine(settings.database_url, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)  # type: ignore[call-overload]
    async with async_session() as db:
        await seed(db, force=force)
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
