"""MuseHub stress-test seed script.

Inserts a rich, realistic dataset that exercises every implemented URL,
every sidebar section, every social feature, every analytics panel, and
every discovery/explore surface.

Scale:
  - 8 users  (gabriel, sofia, marcus, yuki, aaliya, chen, fatou, pierre)
  - 12 repos across 5 genres
  - 30-50 commits per repo (with realistic branch history)
  - 10+ issues per repo, mix of open/closed
  - 4+ PRs per repo (open, merged, closed)
  - 2-4 releases per repo
  - 3-8 sessions per repo
  - Comments, reactions, follows, watches, notifications, forks, view events
  - Commit objects (tracks) with real instrument roles for the breakdown bar

Run inside the container:
  docker compose exec maestro python3 /app/scripts/seed_musehub.py

Idempotent: pass --force to wipe and re-insert.
"""
from __future__ import annotations

import asyncio
import hashlib
import sys
import uuid
from datetime import datetime, timedelta, timezone
from typing import Any

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

from maestro.config import settings
from maestro.db.musehub_models import (
    MusehubBranch,
    MusehubComment,
    MusehubCommit,
    MusehubDownloadEvent,
    MusehubFollow,
    MusehubFork,
    MusehubIssue,
    MusehubNotification,
    MusehubObject,
    MusehubProfile,
    MusehubPullRequest,
    MusehubReaction,
    MusehubRelease,
    MusehubRepo,
    MusehubSession,
    MusehubStar,
    MusehubViewEvent,
    MusehubWatch,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

UTC = timezone.utc


def _now(days: int = 0, hours: int = 0) -> datetime:
    return datetime.now(tz=UTC) - timedelta(days=days, hours=hours)


def _sha(seed: str) -> str:
    return hashlib.sha256(seed.encode()).hexdigest()


def _uid(seed: str) -> str:
    return str(uuid.UUID(bytes=hashlib.md5(seed.encode()).digest()))


# ---------------------------------------------------------------------------
# Constants — stable IDs so URLs never change between re-seeds
# ---------------------------------------------------------------------------

# Users — original community
GABRIEL  = "user-gabriel-001"
SOFIA    = "user-sofia-002"
MARCUS   = "user-marcus-003"
YUKI     = "user-yuki-004"
AALIYA   = "user-aaliya-005"
CHEN     = "user-chen-006"
FATOU    = "user-fatou-007"
PIERRE   = "user-pierre-008"

USERS = [
    (GABRIEL, "gabriel", "Composer & producer. Neo-soul, modal jazz, ambient. All sounds generated by Stori."),
    (SOFIA,   "sofia",   "Classical-meets-electronic. Algorithmic composition. Lover of Nils Frahm."),
    (MARCUS,  "marcus",  "Session keys player turned digital composer. Jazz, funk, everything in between."),
    (YUKI,    "yuki",    "Tokyo-based sound designer. Granular synthesis, algorithmic rhythms, and noise art."),
    (AALIYA,  "aaliya",  "Afrobeat, highlife, and jazz fusion. Lagos → Berlin. Always in motion."),
    (CHEN,    "chen",    "Microtonal explorer. Just intonation, spectral music, extended techniques."),
    (FATOU,   "fatou",   "Griots meet Moog. West African rhythms with modular synthesis."),
    (PIERRE,  "pierre",  "French chanson meets minimalism. Piano, cello, and long silences."),
]

# Users — historical composers and licensed artists (batch-13)
BACH          = "user-bach-000000009"
CHOPIN        = "user-chopin-00000010"
SCOTT_JOPLIN  = "user-sjoplin-0000011"
KEVIN_MACLEOD = "user-kmacleod-000012"
KAI_ENGEL     = "user-kaiengl-000013"

COMPOSER_USERS = [
    (BACH,          "bach",          "Johann Sebastian Bach (1685-1750). Baroque counterpoint, fugue, and harmony. Archive upload by Stori community."),
    (CHOPIN,        "chopin",        "Frédéric Chopin (1810-1849). Romantic piano. Nocturnes, études, ballades. Archive upload by Stori community."),
    (SCOTT_JOPLIN,  "scott_joplin",  "Scott Joplin (1868-1917). King of Ragtime. Maple Leaf Rag, The Entertainer. Archive upload by Stori community."),
    (KEVIN_MACLEOD, "kevin_macleod", "Kevin MacLeod. Cinematic, orchestral, ambient. Thousands of royalty-free compositions. incompetech.com."),
    (KAI_ENGEL,     "kai_engel",     "Kai Engel. Ambient, neoclassical, cinematic. Delicate textures and patient melodies. Free Music Archive."),
]

# All contributors for community-collab cycling (8 existing users)
ALL_CONTRIBUTORS = [
    "gabriel", "sofia", "marcus", "yuki", "aaliya", "chen", "fatou", "pierre",
]

# Repos — original community projects
REPO_NEO_SOUL     = "repo-neo-soul-00000001"
REPO_MODAL_JAZZ   = "repo-modal-jazz-000001"
REPO_AMBIENT      = "repo-ambient-textures-1"
REPO_AFROBEAT     = "repo-afrobeat-grooves-1"
REPO_MICROTONAL   = "repo-microtonal-etudes1"
REPO_DRUM_MACHINE = "repo-drum-machine-00001"
REPO_CHANSON      = "repo-chanson-minimale-1"
REPO_GRANULAR     = "repo-granular-studies-1"
REPO_FUNK_SUITE   = "repo-funk-suite-0000001"
REPO_JAZZ_TRIO    = "repo-jazz-trio-0000001"
REPO_NEO_SOUL_FORK = "repo-neo-soul-fork-0001"
REPO_AMBIENT_FORK  = "repo-ambient-fork-0001"

# Repos — 12 genre archive repos (batch-13)
REPO_WTC          = "repo-well-tempered-cl01"  # bach/well-tempered-clavier
REPO_GOLDBERG     = "repo-goldberg-vars00001"  # bach/goldberg-variations
REPO_NOCTURNES    = "repo-chopin-nocturnes01"  # chopin/nocturnes
REPO_MAPLE_LEAF   = "repo-maple-leaf-rag0001"  # scott_joplin/maple-leaf-rag
REPO_CIN_STRINGS  = "repo-cinematic-strngs01"  # kevin_macleod/cinematic-strings
REPO_KAI_AMBIENT  = "repo-kai-ambient-txtr01"  # kai_engel/ambient-textures
REPO_NEO_BAROQUE  = "repo-neo-baroque-000001"  # gabriel/neo-baroque
REPO_JAZZ_CHOPIN  = "repo-jazz-chopin-000001"  # aaliya/jazz-chopin
REPO_RAGTIME_EDM  = "repo-ragtime-edm-000001"  # marcus/ragtime-edm
REPO_FILM_SCORE   = "repo-film-score-000001"   # chen/film-score
REPO_POLYRHYTHM   = "repo-polyrhythm-000001"   # fatou/polyrhythm
REPO_COMMUNITY    = "repo-community-collab01"  # gabriel/community-collab

REPOS: list[dict[str, Any]] = [
    dict(repo_id=REPO_NEO_SOUL, name="Neo-Soul Experiment", owner="gabriel", slug="neo-soul-experiment",
         owner_user_id=GABRIEL, visibility="public",
         description="A funk-influenced neo-soul project exploring polyrhythmic grooves in F# minor.",
         tags=["neo-soul", "funk", "F# minor", "polyrhythm", "bass-heavy"],
         key_signature="F# minor", tempo_bpm=92, days_ago=90, star_count=24, fork_count=3),
    dict(repo_id=REPO_MODAL_JAZZ, name="Modal Jazz Sketches", owner="gabriel", slug="modal-jazz-sketches",
         owner_user_id=GABRIEL, visibility="public",
         description="Exploring Dorian and Phrygian modes. Miles Davis and Coltrane are the north stars.",
         tags=["jazz", "modal", "Dorian", "Phrygian", "piano", "trumpet"],
         key_signature="D Dorian", tempo_bpm=120, days_ago=60, star_count=18, fork_count=2),
    dict(repo_id=REPO_AMBIENT, name="Ambient Textures Vol. 1", owner="sofia", slug="ambient-textures-vol-1",
         owner_user_id=SOFIA, visibility="public",
         description="Slow-evolving pads and generative arpeggios. Inspired by Eno and Nils Frahm.",
         tags=["ambient", "generative", "pads", "Eb major", "slow"],
         key_signature="Eb major", tempo_bpm=60, days_ago=45, star_count=31, fork_count=5),
    dict(repo_id=REPO_AFROBEAT, name="Afrobeat Grooves", owner="aaliya", slug="afrobeat-grooves",
         owner_user_id=AALIYA, visibility="public",
         description="High-life meets contemporary production. Polyrhythmic percussion layers.",
         tags=["afrobeat", "highlife", "polyrhythm", "Lagos", "percussion"],
         key_signature="G major", tempo_bpm=128, days_ago=30, star_count=42, fork_count=6),
    dict(repo_id=REPO_MICROTONAL, name="Microtonal Études", owner="chen", slug="microtonal-etudes",
         owner_user_id=CHEN, visibility="public",
         description="31-TET explorations. Spectral harmony and just intonation studies.",
         tags=["microtonal", "spectral", "31-TET", "just intonation", "experimental"],
         key_signature="C (31-TET)", tempo_bpm=76, days_ago=25, star_count=9, fork_count=1),
    dict(repo_id=REPO_DRUM_MACHINE, name="808 Variations", owner="fatou", slug="808-variations",
         owner_user_id=FATOU, visibility="public",
         description="West African polyrhythm patterns through an 808 and modular synthesis.",
         tags=["drums", "808", "polyrhythm", "West Africa", "modular"],
         key_signature="A minor", tempo_bpm=100, days_ago=20, star_count=15, fork_count=2),
    dict(repo_id=REPO_CHANSON, name="Chanson Minimale", owner="pierre", slug="chanson-minimale",
         owner_user_id=PIERRE, visibility="public",
         description="French chanson miniatures. Piano and cello. Silence as a compositional element.",
         tags=["chanson", "minimalism", "piano", "cello", "French"],
         key_signature="A major", tempo_bpm=52, days_ago=15, star_count=7, fork_count=0),
    dict(repo_id=REPO_GRANULAR, name="Granular Studies", owner="yuki", slug="granular-studies",
         owner_user_id=YUKI, visibility="public",
         description="Granular synthesis research — texture, density, scatter. Source material: found sounds.",
         tags=["granular", "synthesis", "experimental", "Tokyo", "texture"],
         key_signature="E minor", tempo_bpm=70, days_ago=10, star_count=12, fork_count=1),
    dict(repo_id=REPO_FUNK_SUITE, name="Funk Suite No. 1", owner="marcus", slug="funk-suite-no-1",
         owner_user_id=MARCUS, visibility="public",
         description="A four-movement funk suite. Electric piano, clavinet, wah bass, and pocket drums.",
         tags=["funk", "electric piano", "clavinet", "groove", "suite"],
         key_signature="E minor", tempo_bpm=108, days_ago=50, star_count=28, fork_count=4),
    dict(repo_id=REPO_JAZZ_TRIO, name="Jazz Trio Sessions", owner="marcus", slug="jazz-trio-sessions",
         owner_user_id=MARCUS, visibility="public",
         description="Live-feel jazz trio recordings. Piano, double bass, brushed snare. Standards reimagined.",
         tags=["jazz", "trio", "piano", "bass", "standards"],
         key_signature="Bb major", tempo_bpm=138, days_ago=35, star_count=19, fork_count=2),
    # Forked repos (private — for the fork sidebar section)
    dict(repo_id=REPO_NEO_SOUL_FORK, name="Neo-Soul Experiment", owner="marcus", slug="neo-soul-experiment",
         owner_user_id=MARCUS, visibility="private",
         description="Fork of gabriel/neo-soul-experiment — Marcus's arrangement experiments.",
         tags=["neo-soul", "funk", "F# minor", "fork"],
         key_signature="F# minor", tempo_bpm=92, days_ago=10, star_count=0, fork_count=0),
    dict(repo_id=REPO_AMBIENT_FORK, name="Ambient Textures Vol. 1", owner="yuki", slug="ambient-textures-vol-1",
         owner_user_id=YUKI, visibility="private",
         description="Fork of sofia/ambient-textures-vol-1 — Yuki's granular re-imagining.",
         tags=["ambient", "granular", "fork"],
         key_signature="Eb major", tempo_bpm=60, days_ago=5, star_count=0, fork_count=0),
]

# Genre archive repos — batch-13 additions with structured muse_tags
GENRE_REPOS: list[dict[str, Any]] = [
    dict(repo_id=REPO_WTC, name="The Well-Tempered Clavier", owner="bach", slug="well-tempered-clavier",
         owner_user_id=BACH, visibility="public",
         description="Bach's 48 preludes and fugues — one in each major and minor key. The definitive study in tonal harmony.",
         tags=["genre:baroque", "key:C", "key:Am", "key:G", "key:F", "key:Bb", "stage:released", "emotion:serene", "emotion:complex"],
         key_signature="C major (all 24 keys)", tempo_bpm=72, days_ago=365, star_count=88, fork_count=12),
    dict(repo_id=REPO_GOLDBERG, name="Goldberg Variations", owner="bach", slug="goldberg-variations",
         owner_user_id=BACH, visibility="public",
         description="Aria with 30 variations. Bach's monumental keyboard work — from simple canon to ornate arabesque.",
         tags=["genre:baroque", "stage:released", "emotion:joyful", "emotion:melancholic", "key:G"],
         key_signature="G major", tempo_bpm=60, days_ago=350, star_count=74, fork_count=9),
    dict(repo_id=REPO_NOCTURNES, name="Nocturnes", owner="chopin", slug="nocturnes",
         owner_user_id=CHOPIN, visibility="public",
         description="21 nocturnes for solo piano — poetry in sound. Lyrical melodies over arpeggiated left-hand accompaniment.",
         tags=["genre:romantic", "emotion:melancholic", "emotion:tender", "stage:released", "key:Bb", "key:Eb"],
         key_signature="Bb minor", tempo_bpm=58, days_ago=300, star_count=62, fork_count=8),
    dict(repo_id=REPO_MAPLE_LEAF, name="Maple Leaf Rag", owner="scott_joplin", slug="maple-leaf-rag",
         owner_user_id=SCOTT_JOPLIN, visibility="public",
         description="The rag that launched a revolution. Syncopated right-hand melody over an oom-pah bass. The birth of ragtime.",
         tags=["genre:ragtime", "emotion:playful", "stage:released", "key:Ab", "tempo:march"],
         key_signature="Ab major", tempo_bpm=100, days_ago=280, star_count=51, fork_count=7),
    dict(repo_id=REPO_CIN_STRINGS, name="Cinematic Strings", owner="kevin_macleod", slug="cinematic-strings",
         owner_user_id=KEVIN_MACLEOD, visibility="public",
         description="Orchestral string textures for cinematic use. Builds from delicate pianissimo to full tutti climax.",
         tags=["genre:cinematic", "emotion:triumphant", "stage:released", "tempo:adagio", "key:D"],
         key_signature="D minor", tempo_bpm=64, days_ago=180, star_count=43, fork_count=5),
    dict(repo_id=REPO_KAI_AMBIENT, name="Ambient Textures", owner="kai_engel", slug="ambient-textures",
         owner_user_id=KAI_ENGEL, visibility="public",
         description="Patient, breathing soundscapes. Piano, strings, and silence woven into evolving ambient fields.",
         tags=["genre:ambient", "emotion:serene", "stage:released", "tempo:largo", "key:C"],
         key_signature="C major", tempo_bpm=50, days_ago=150, star_count=38, fork_count=4),
    dict(repo_id=REPO_NEO_BAROQUE, name="Neo-Baroque Studies", owner="gabriel", slug="neo-baroque",
         owner_user_id=GABRIEL, visibility="public",
         description="What if Bach wrote jazz? Modal harmony and quartal voicings dressed in baroque counterpoint.",
         tags=["genre:baroque", "genre:jazz", "stage:rough-mix", "emotion:complex", "ref:bach", "key:D"],
         key_signature="D Dorian", tempo_bpm=84, days_ago=120, star_count=29, fork_count=3),
    dict(repo_id=REPO_JAZZ_CHOPIN, name="Jazz Chopin", owner="aaliya", slug="jazz-chopin",
         owner_user_id=AALIYA, visibility="public",
         description="Chopin nocturnes reharmonized through a Coltrane lens. Rootless voicings, tritone substitutions, and more.",
         tags=["genre:jazz", "genre:romantic", "emotion:tender", "ref:chopin", "ref:coltrane", "stage:mixing"],
         key_signature="Bb minor", tempo_bpm=68, days_ago=90, star_count=34, fork_count=4),
    dict(repo_id=REPO_RAGTIME_EDM, name="Ragtime EDM", owner="marcus", slug="ragtime-edm",
         owner_user_id=MARCUS, visibility="public",
         description="Scott Joplin meets the dancefloor. Syncopated MIDI melodies over trap hi-hats and house kick patterns.",
         tags=["genre:edm", "genre:ragtime", "stage:production", "emotion:playful", "tempo:dance"],
         key_signature="Ab major", tempo_bpm=128, days_ago=70, star_count=26, fork_count=3),
    dict(repo_id=REPO_FILM_SCORE, name="Film Score — Untitled", owner="chen", slug="film-score",
         owner_user_id=CHEN, visibility="public",
         description="Three-act cinematic score. Microtonal tension in Act I, spectral climax in Act II, resolution in Act III.",
         tags=["genre:cinematic", "emotion:tense", "emotion:triumphant", "stage:mixing", "key:C"],
         key_signature="C (31-TET)", tempo_bpm=72, days_ago=55, star_count=18, fork_count=2),
    dict(repo_id=REPO_POLYRHYTHM, name="Polyrhythm Studies", owner="fatou", slug="polyrhythm",
         owner_user_id=FATOU, visibility="public",
         description="West African rhythmic philosophy through a modular lens. 7-over-4, 5-over-3, and beyond.",
         tags=["genre:afrobeats", "emotion:playful", "emotion:energetic", "stage:rough-mix", "tempo:polyrhythm"],
         key_signature="A minor", tempo_bpm=92, days_ago=35, star_count=21, fork_count=2),
    dict(repo_id=REPO_COMMUNITY, name="Community Collab", owner="gabriel", slug="community-collab",
         owner_user_id=GABRIEL, visibility="public",
         description="An open canvas for all eight contributors. Every genre, every voice, one evolving composition.",
         tags=["genre:baroque", "genre:jazz", "genre:romantic", "genre:ragtime", "genre:cinematic",
               "genre:ambient", "genre:edm", "genre:afrobeats", "emotion:serene", "emotion:complex",
               "emotion:joyful", "emotion:melancholic", "emotion:tender", "emotion:playful",
               "emotion:energetic", "emotion:triumphant", "emotion:tense", "stage:rough-mix"],
         key_signature="C major", tempo_bpm=90, days_ago=200, star_count=95, fork_count=15),
]


# ---------------------------------------------------------------------------
# Commit templates per repo
# ---------------------------------------------------------------------------

def _make_commits(repo_id: str, repo_key: str, n: int) -> list[dict[str, Any]]:
    """Generate n realistic commits for repo_key with a branching history."""
    TEMPLATES = {
        "neo-soul": [
            ("init: establish F# minor groove template at 92 BPM", "gabriel"),
            ("feat(bass): add polyrhythmic bass line — 3-against-4 pulse", "gabriel"),
            ("feat(keys): Rhodes chord voicings with upper-structure triads", "gabriel"),
            ("refactor(drums): humanize ghost notes, tighten hi-hat velocity", "gabriel"),
            ("feat(strings): bridge string section — section:bridge track:strings", "gabriel"),
            ("feat(horns): sketch trumpet + alto sax counter-melody", "gabriel"),
            ("fix(keys): resolve voice-leading parallel fifths in bar 7", "gabriel"),
            ("feat(guitar): add scratch guitar rhythm in chorus — track:guitar", "gabriel"),
            ("refactor(bass): tighten sub-bass at bar 13 to avoid muddiness", "marcus"),
            ("feat(perc): add shaker and tambourine for groove density", "gabriel"),
            ("fix(timing): realign hi-hat to quantize grid after humanize", "gabriel"),
            ("feat(choir): add background vocal pad — ooh/aah — section:chorus", "gabriel"),
            ("refactor(mix): reduce Rhodes level -3dB, open hi-hat +2dB", "marcus"),
            ("feat(bridge): call-and-response horn arrangement — bars 25-32", "gabriel"),
            ("fix(harmony): correct augmented chord spelling in turnaround", "gabriel"),
            ("feat(strings): counterpoint violin line against bass in verse", "gabriel"),
            ("refactor(drums): add kick variation in bar 4 of each 8-bar phrase", "marcus"),
            ("feat(organ): add organ swell in pre-chorus — track:organ", "gabriel"),
            ("fix(keys): remove accidental octave doubling in Rhodes voicing", "gabriel"),
            ("feat(bass): slap variation for funk breakdown — section:breakdown", "marcus"),
            ("refactor(horns): rewrite alto sax response phrase — cleaner contour", "gabriel"),
            ("feat(perc): cowbell accent on beat 3 of bar 2 — groove:funk", "gabriel"),
            ("feat(strings): pizzicato countermelody — bars 17-24", "gabriel"),
            ("fix(guitar): tighten wah envelope attack — reduce pre-delay", "gabriel"),
            ("feat(voice): lead vocal melody sketch — section:verse track:vocals", "gabriel"),
        ],
        "modal-jazz": [
            ("init: D Dorian vamp at 120 BPM — piano + bass", "gabriel"),
            ("feat(melody): Coltrane-inspired pentatonic runs over IV chord", "gabriel"),
            ("feat(drums): brush kit — swing factor 0.65", "gabriel"),
            ("experiment: Phrygian dominant bridge — E Phrygian Dominant", "gabriel"),
            ("feat(piano): add McCoy Tyner quartal voicings in A section", "gabriel"),
            ("fix(bass): correct walking bass note on bar 9 beat 3", "gabriel"),
            ("feat(trumpet): head melody sketch — 12-bar AABA form", "gabriel"),
            ("refactor(drums): increase ride cymbal bell accent frequency", "gabriel"),
            ("feat(piano): bebop left-hand comp pattern — bars 1-8", "marcus"),
            ("fix(melody): resolve blue note to major 3rd at phrase end", "gabriel"),
            ("feat(bass): pedal point through Phrygian section — E pedal", "gabriel"),
            ("feat(drums): hi-hat splash on beat 4 of turnaround", "gabriel"),
            ("refactor(piano): revoice III chord as tritone substitution", "gabriel"),
            ("feat(guitar): Freddie Green-style chord stabs — 4-to-the-bar", "marcus"),
            ("fix(trumpet): fix pitch of low C# — use Eb enharmonic", "gabriel"),
            ("feat(piano): out-chorus with McCoy quartal clusters", "gabriel"),
            ("feat(bass): counter-rhythm 2-bar fill after trumpet solo", "gabriel"),
        ],
        "ambient": [
            ("init: Eb major pad foundation — slow attack 4s release 8s", "sofia"),
            ("feat(arp): generative 16th-note arpeggiator — random seed 42", "sofia"),
            ("feat(texture): granular string texture layer — section:intro", "yuki"),
            ("fix(arp): reduce velocity variance — sounds too mechanical", "sofia"),
            ("feat(pad): add sub-octave layer for warmth — section:middle", "sofia"),
            ("feat(bells): wind chime texture — 7th partial harmonic series", "yuki"),
            ("refactor(arp): increase note-length randomization range", "sofia"),
            ("feat(drone): Eb pedal drone — bowed brass harmonic", "pierre"),
            ("fix(texture): reduce granular density in intro — too busy", "yuki"),
            ("feat(reverb): add convolution reverb impulse — Norwegian church", "sofia"),
            ("feat(pad): second pad layer — inversion of root chord", "sofia"),
            ("refactor(arp): change arpeggio direction — ascending + descending", "sofia"),
            ("feat(texture): filtered noise texture — high shelf +6dB", "yuki"),
            ("fix(drone): tune drone to equal temperament Eb", "sofia"),
            ("feat(melody): sparse piano melody — whole notes — section:climax", "pierre"),
            ("feat(fade): 3-minute fade out — linear to -80dB", "sofia"),
            ("refactor(mix): reduce string texture -2dB to sit behind pad", "yuki"),
            ("fix(arp): fix stuck note at bar 64 — midi note-off missing", "sofia"),
        ],
        "afrobeat": [
            ("init: G major groove at 128 BPM — 12/8 polyrhythm", "aaliya"),
            ("feat(perc): traditional talking drum pattern — track:tama", "aaliya"),
            ("feat(guitar): highlife guitar pattern — interlocking rhythm", "aaliya"),
            ("feat(bass): electric bass groove — root-fifth walking pattern", "aaliya"),
            ("feat(horns): brass unison figure — bars 1-4", "aaliya"),
            ("refactor(perc): tighten conga timing — reduce humanize variance", "fatou"),
            ("feat(keys): Fender Rhodes stabs — track:keys", "aaliya"),
            ("fix(guitar): fix choke on open string — add palm mute", "aaliya"),
            ("feat(choir): call-and-response vocal arrangement", "aaliya"),
            ("feat(bass): syncopated fills at section transitions", "aaliya"),
            ("refactor(horns): split alto and tenor lines — 3rd apart", "aaliya"),
            ("feat(perc): shekere layer — steady eighth-note pulse", "fatou"),
            ("fix(mix): reduce vocal level in verse — instrumental focus", "aaliya"),
            ("feat(guitar): second guitar — rhythmic scratches on offbeat", "aaliya"),
            ("feat(bass): slap bass hook for chorus energy boost", "aaliya"),
            ("refactor(drums): add more snare ghost notes — Questlove style", "fatou"),
            ("feat(keys): organ swell into chorus — track:organ", "aaliya"),
            ("fix(perc): fix timing drift on conga in bar 32", "fatou"),
            ("feat(strings): string overdub — Fela-inspired octave line", "aaliya"),
            ("feat(voice): lead vocal melody — Yoruba lyric sketch", "aaliya"),
        ],
        "microtonal": [
            ("init: C (31-TET) drone exploration at 76 BPM", "chen"),
            ("feat(harmony): otonal hexad — 4:5:6:7:9:11", "chen"),
            ("feat(melody): quarter-tone scale ascending line", "chen"),
            ("fix(tuning): correct 7th partial — was off by 3 cents", "chen"),
            ("feat(rhythm): Messiaen mode 3 rhythm grid", "chen"),
            ("feat(texture): spectral filtered noise — harmonic series", "chen"),
            ("refactor(melody): retrograde inversion of opening motif", "chen"),
            ("feat(bass): undertone series pedal — utonal foundation", "chen"),
            ("fix(harmony): resolve voice-leading microtonal step error", "chen"),
            ("feat(perc): non-retrogradable rhythm in timpani", "chen"),
            ("feat(strings): col legno battuto technique — quarter-tone gliss", "chen"),
            ("refactor(harmony): substitute Ptolemy's intense chromatic", "chen"),
            ("feat(woodwinds): multiphonics — clarinet + flute", "chen"),
            ("fix(tuning): recalibrate piano to equal 31-TET temperament", "chen"),
        ],
        "drums": [
            ("init: A minor 808 foundation at 100 BPM", "fatou"),
            ("feat(kick): four-on-the-floor with sub-frequency duck", "fatou"),
            ("feat(snare): syncopated snare with flam accent", "fatou"),
            ("feat(hihat): 16th-note hi-hat with velocity curve", "fatou"),
            ("feat(perc): djembe pattern — traditional Mandinka rhythm", "fatou"),
            ("feat(808): 808 bass note on root — 100ms decay", "fatou"),
            ("refactor(kick): tune 808 kick to key center A — 110Hz", "fatou"),
            ("fix(hihat): remove double-triggered hi-hat on beat 3", "fatou"),
            ("feat(perc): shaker accent pattern — offbeat sixteenths", "fatou"),
            ("feat(snare): ghost note velocity humanize — ±12 velocity", "fatou"),
            ("feat(808): sub-bass movement — root to 5th fills", "fatou"),
            ("refactor(perc): layer djembe with finger drum machine", "fatou"),
            ("feat(crash): crash on bar 9 downbeat — section transition", "fatou"),
        ],
        "chanson": [
            ("init: A major sketch — piano solo motif at 52 BPM", "pierre"),
            ("feat(piano): left-hand ostinato — arpeggiated 9th chord", "pierre"),
            ("feat(cello): pizzicato bass line — bars 1-8", "pierre"),
            ("feat(piano): theme A — 8-bar melody in upper voice", "pierre"),
            ("feat(cello): sustained cello counterpoint — bars 9-16", "pierre"),
            ("refactor(piano): reduce left-hand density — let melody breathe", "pierre"),
            ("feat(piano): theme B in relative minor — F# minor", "pierre"),
            ("fix(cello): bowings — ensure smooth legato at bar 12", "pierre"),
            ("feat(piano): coda — augmented theme A in parallel 10ths", "pierre"),
            ("feat(silence): 4-bar rest before final chord — dynamic contrast", "pierre"),
            ("feat(cello): col legno tremolo — extended technique", "pierre"),
            ("refactor(harmony): substitute V7 with bVII for chanson flavour", "pierre"),
        ],
        "granular": [
            ("init: E minor granular pad — source: rain recording", "yuki"),
            ("feat(scatter): random scatter algorithm — grain size 20-80ms", "yuki"),
            ("feat(density): grain density envelope — sparse to dense", "yuki"),
            ("feat(pitch): pitch randomization ±0.3 semitones", "yuki"),
            ("feat(texture): city ambience layer — Tokyo train station", "yuki"),
            ("fix(phase): fix grain phase correlation — reduce flamming", "yuki"),
            ("feat(filter): formant filter on granular output — vowel morph", "yuki"),
            ("refactor(scatter): increase random seed variation per bar", "yuki"),
            ("feat(rhythm): rhythmic granular — sync to 70 BPM sixteenths", "yuki"),
            ("fix(tuning): retune pitch center to E — was detuned +0.5st", "yuki"),
            ("feat(reverb): 8-second hall reverb tail — late reflections only", "yuki"),
            ("feat(mod): LFO modulation on grain position — 0.3Hz triangle", "yuki"),
        ],
        "funk-suite": [
            ("init: E minor funk groove at 108 BPM — Mvt. I", "marcus"),
            ("feat(bass): wah-wah bass hook — bars 1-4 — track:bass", "marcus"),
            ("feat(keys): electric piano chord voicings — tight stabs", "marcus"),
            ("feat(clavinet): clavinet riff — bars 5-8", "marcus"),
            ("feat(drums): pocket drum groove — ghost notes on snare", "marcus"),
            ("feat(guitar): rhythm guitar — interlocking with clavinet", "marcus"),
            ("feat(horns): brass hits on the upbeat — track:horns", "marcus"),
            ("refactor(bass): tighten wah envelope attack for more snap", "marcus"),
            ("feat(keys): Rhodes solo in Mvt. II — Dorian mode", "marcus"),
            ("fix(guitar): remove string buzz on open D", "marcus"),
            ("feat(bass): slap funk breakdown — Mvt. II outro", "marcus"),
            ("feat(perc): add congas — Afro-Cuban polyrhythm layer", "marcus"),
            ("feat(keys): B3 organ swell — Mvt. III transition", "marcus"),
            ("refactor(drums): accent hi-hat on the e's — open 16th feel", "marcus"),
            ("fix(horns): retune brass — flat by 8 cents on high notes", "marcus"),
            ("feat(bass): octave bass walk into chorus — track:bass", "marcus"),
            ("feat(clavinet): filtered clavinet — muted pickstyle", "marcus"),
            ("fix(keys): fix missed chord on beat 4 bar 22", "marcus"),
            ("feat(drums): Mvt. IV — double-time feel — hi-hat 16th groove", "marcus"),
            ("feat(bass): fretless bass for Mvt. IV — floating groove", "marcus"),
        ],
        "jazz-trio": [
            ("init: Bb major vamp — piano trio at 138 BPM", "marcus"),
            ("feat(piano): comping pattern — shell voicings 3-7", "marcus"),
            ("feat(bass): walking bass — Bb major standard changes", "marcus"),
            ("feat(drums): brushed snare pattern — triplet feel", "marcus"),
            ("feat(piano): solo chorus 1 — pentatonic approach", "marcus"),
            ("feat(bass): bass solo feature — rubato", "marcus"),
            ("feat(drums): trading 4s — kit break response", "marcus"),
            ("refactor(piano): reharmonize bridge — tritone subs", "marcus"),
            ("feat(piano): stride left hand in final chorus", "marcus"),
            ("fix(bass): fix intonation on F# — adjust finger placement", "marcus"),
            ("feat(drums): add brushed cymbal roll into solo sections", "marcus"),
            ("feat(piano): ballad tempo reduction for outro — ♩=72", "marcus"),
            ("refactor(bass): add counterpoint line during piano comping", "marcus"),
            ("fix(drums): remove extraneous kick note on bar 9", "marcus"),
            ("feat(piano): final cadenza — rubato", "marcus"),
        ],
        # Genre archive repos — batch-13
        "wtc": [
            ("init: Book I — Prelude No.1 in C major — arpeggiated harmony", "gabriel"),
            ("feat(fugue): Fugue No.1 in C major — 4-voice exposition", "gabriel"),
            ("feat(prelude): Prelude No.2 in C minor — perpetual motion 16ths", "sofia"),
            ("feat(fugue): Fugue No.2 in C minor — chromatic subject", "gabriel"),
            ("feat(prelude): Prelude No.3 in C# major — arpeggiated texture", "chen"),
            ("feat(fugue): Fugue No.3 in C# major — 3-voice stretto", "gabriel"),
            ("refactor(harmony): correct spelling of diminished 7th in bar 8", "pierre"),
            ("feat(prelude): Prelude No.4 in C# minor — lyrical melody", "gabriel"),
            ("feat(fugue): Fugue No.4 in C# minor — 5-voice exposition", "sofia"),
            ("feat(prelude): Prelude No.5 in D major — driving 16th notes", "gabriel"),
            ("feat(fugue): Fugue No.5 in D major — invertible counterpoint", "chen"),
            ("fix(voice-leading): resolve parallel 5ths in C major fugue bar 14", "gabriel"),
            ("feat(prelude): Prelude No.6 in D minor — expressive chromatics", "pierre"),
            ("feat(fugue): Fugue No.6 in D minor — augmentation in bass", "gabriel"),
            ("feat(prelude): Prelude No.7 in Eb major — ornate passagework", "sofia"),
            ("feat(fugue): Fugue No.7 in Eb major — inversion of subject", "gabriel"),
            ("refactor(ornamentation): add trills per Baroque convention — bars 1-4", "chen"),
            ("feat(prelude): Prelude No.8 in Eb minor — chromatic descent", "gabriel"),
            ("feat(fugue): Fugue No.8 in Eb minor — 3-voice with episode", "pierre"),
            ("feat(prelude): Prelude No.9 in E major — binary form", "gabriel"),
            ("feat(fugue): Fugue No.9 in E major — motivic development", "sofia"),
            ("fix(tuning): retune to equal temperament from well-temperament", "chen"),
            ("feat(prelude): Prelude No.10 in E minor — two-part invention style", "gabriel"),
            ("feat(fugue): Fugue No.10 in E minor — rhythmic diminution", "gabriel"),
            ("feat(book2): Book II — Prelude No.1 in C major — extended version", "sofia"),
            ("feat(book2): Fugue No.1 BK2 in C major — 4-voice with tonal answer", "gabriel"),
            ("feat(book2): Prelude No.2 BK2 in C minor — turbulent arpeggios", "pierre"),
            ("feat(book2): Fugue No.2 BK2 — chromatic subject, 4 voices", "gabriel"),
            ("refactor(dynamics): add hairpin dynamics per Urtext edition", "sofia"),
            ("feat(book2): Prelude No.3 BK2 in C# major — serene cantabile", "gabriel"),
        ],
        "goldberg": [
            ("init: Goldberg Aria — sarabande in G major, ornate upper voice", "gabriel"),
            ("feat(var1): Variation 1 — two-voice in parallel 3rds", "gabriel"),
            ("feat(var2): Variation 2 — one voice per hand, canonic imitation", "sofia"),
            ("feat(var3): Variation 3 — canon at the unison", "gabriel"),
            ("feat(var4): Variation 4 — robust 4-voice passepied", "pierre"),
            ("feat(var5): Variation 5 — hand-crossing, one voice each hand", "gabriel"),
            ("feat(var6): Variation 6 — canon at the second", "sofia"),
            ("feat(var7): Variation 7 — gigue in 6/8, dance character", "gabriel"),
            ("feat(var8): Variation 8 — two-voice inversion in 3rds and 6ths", "chen"),
            ("feat(var13): Variation 13 — lyrical aria-like melody, experimental rubato", "gabriel"),
            ("fix(ornaments): correct trill resolution in Variation 13 bar 9", "sofia"),
            ("feat(var25): Variation 25 — chromatic aria, the emotional heart", "gabriel"),
            ("feat(var30): Variation 30 — Quodlibet, quotes folk songs", "gabriel"),
            ("feat(aria-reprise): Aria da capo — return of opening theme", "pierre"),
            ("refactor(voicing): ensure aria melody sits above all inner voices", "gabriel"),
            ("fix(voice-leading): remove parallel octaves in Variation 4 bar 12", "sofia"),
            ("refactor(tempo): apply consistent note values in 3/4 Variations", "gabriel"),
            ("feat(var21): Variation 21 — chromatic canon at the 7th", "chen"),
        ],
        "nocturnes": [
            ("init: Op.9 No.1 in Bb minor — gentle arpeggiated bass, yearning melody", "aaliya"),
            ("feat(op9-2): Op.9 No.2 in Eb major — the iconic theme, ornate reprise", "aaliya"),
            ("feat(op9-3): Op.9 No.3 in B major — agitated middle section", "gabriel"),
            ("feat(op15-1): Op.15 No.1 in F major — pastoral melody, stormy development", "aaliya"),
            ("feat(op15-2): Op.15 No.2 in F# major — murmuring bass, cantabile melody", "sofia"),
            ("feat(op15-3): Op.15 No.3 in G minor — solemn choral opening", "aaliya"),
            ("feat(op27-1): Op.27 No.1 in C# minor — tragic opening, ecstatic climax", "gabriel"),
            ("feat(op27-2): Op.27 No.2 in Db major — sustained melody, ornate inner voice", "aaliya"),
            ("refactor(rubato): add tempo fluctuation markings per Chopin's own notation", "pierre"),
            ("fix(pedaling): correct sustain pedal placement in Op.9 No.2 bar 5", "aaliya"),
            ("feat(op32-1): Op.32 No.1 in B major — introspective, questioning end", "sofia"),
            ("feat(op32-2): Op.32 No.2 in Ab major — gentle but harmonically complex", "aaliya"),
            ("feat(op37-1): Op.37 No.1 in G minor — chorale-like, organistic", "gabriel"),
            ("feat(op37-2): Op.37 No.2 in G major — barcarolle-style 6/8", "aaliya"),
            ("refactor(ornamentation): add mordents and grace notes per autograph", "sofia"),
            ("fix(voice-leading): eliminate voice crossing in Op.15 No.3 bar 7", "aaliya"),
            ("feat(op48-1): Op.48 No.1 in C minor — grand and tragic", "gabriel"),
            ("feat(op48-2): Op.48 No.2 in F# minor — agitated and restless", "aaliya"),
            ("feat(op55-1): Op.55 No.1 in F minor — melancholic cantabile", "sofia"),
            ("feat(op55-2): Op.55 No.2 in Eb major — flowing, conversational", "aaliya"),
            ("feat(op62-1): Op.62 No.1 in B major — late style, fragmented ornament", "gabriel"),
            ("feat(op62-2): Op.62 No.2 in E major — tender farewell, inner voices", "aaliya"),
        ],
        "maple-leaf": [
            ("init: Maple Leaf Rag in Ab major — 4/4 at 100 BPM", "marcus"),
            ("feat(A): Section A — syncopated melody over oom-pah bass, bars 1-16", "marcus"),
            ("feat(A-repeat): Section A repeat with octave doubling in melody", "gabriel"),
            ("feat(B): Section B — contrast, moves to Eb major", "marcus"),
            ("feat(B-repeat): Section B repeat — velocity humanized", "marcus"),
            ("feat(C): Section C (trio) — moves to Db major, more lyrical", "marcus"),
            ("feat(C-repeat): Section C repeat with improvised embellishment", "gabriel"),
            ("feat(D): Section D — returns to Ab, triumphant restatement", "marcus"),
            ("refactor(bass): tighten oom-pah bass timing — was 8ms ahead", "marcus"),
            ("fix(melody): correct grace note in bar 9 — was wrong pitch Eb not D", "gabriel"),
            ("feat(slow): slow-version — halftime feel, rubato allowed", "marcus"),
            ("feat(slow): slow-version extended ornaments in melody", "gabriel"),
            ("feat(edm): marcus-edm-remix — trap hi-hats under ragtime melody", "marcus"),
            ("feat(edm): marcus-edm-remix — 808 bass replacing oom-pah pattern", "marcus"),
        ],
        "cinematic-strings": [
            ("init: Cinematic Strings in D minor — string orchestra at 64 BPM", "gabriel"),
            ("feat(intro): solo cello theme — bars 1-8 — pp, col arco", "chen"),
            ("feat(build): violas enter — pizzicato counter-rhythm, bars 9-16", "gabriel"),
            ("feat(build): second violins add sustained harmonic pad", "sofia"),
            ("feat(climax): full orchestra tutti — bars 33-40 — ff", "gabriel"),
            ("feat(climax): timpani and brass reinforcement at climax peak", "chen"),
            ("feat(resolution): strings return to solo cello — reprise of theme", "gabriel"),
            ("refactor(dynamics): smooth crescendo from pp to ff over 32 bars", "sofia"),
            ("fix(intonation): retune violin II section — was sharp by 5 cents", "gabriel"),
            ("feat(orchestral): orchestral branch — add oboe and clarinet doubling", "chen"),
            ("feat(orchestral): French horn countermelody in orchestral version", "gabriel"),
            ("feat(piano): stripped-piano branch — piano reduction of string score", "pierre"),
            ("feat(piano): add pedal markings to piano reduction", "sofia"),
            ("refactor(tempo): add ritardando at bar 38 for dramatic pause", "gabriel"),
            ("fix(articulation): add sul ponticello marking to Variation 2 strings", "chen"),
        ],
        "kai-ambient": [
            ("init: Kai Engel ambient field — C major, slow morphing pad", "pierre"),
            ("feat(pad1): first layer — high strings, ppp, infinite sustain", "pierre"),
            ("feat(pad2): second pad — piano harmonics, prepared technique", "sofia"),
            ("feat(piano): sparse piano melody — whole notes, bars 9-24", "pierre"),
            ("feat(v1): v1 branch — original release version, 8-minute version", "pierre"),
            ("refactor(v1): v1 — master level adjusted to -14 LUFS", "sofia"),
            ("feat(v2): v2-extended — added 4-minute drone coda", "pierre"),
            ("feat(v2): v2-extended — new string layer in coda, sul tasto", "sofia"),
            ("fix(phase): reduce stereo width in pad2 to avoid phase cancellation", "pierre"),
            ("refactor(mix): filter low end on pad1 — HPF at 80Hz", "pierre"),
        ],
        "neo-baroque": [
            ("init: Neo-Baroque in D Dorian — harpsichord + electric bass at 84 BPM", "gabriel"),
            ("feat(counterpoint): two-voice invention — right hand melody, left hand bass", "gabriel"),
            ("feat(jazz): jazz-voicings branch — quartal harmony replaces triads", "gabriel"),
            ("feat(jazz): tritone substitution in bar 8 turnaround — jazz-voicings", "marcus"),
            ("feat(jazz): rootless 9th voicings in right hand — jazz-voicings", "gabriel"),
            ("feat(harmony): harmonic sequence — descending 5ths in bass", "gabriel"),
            ("feat(rhythm): syncopated baroque rhythm — quarter-note displacement", "gabriel"),
            ("feat(edm): edm-bassline branch — 808 sub bass under baroque melody", "marcus"),
            ("feat(edm): four-on-the-floor kick added — edm-bassline", "gabriel"),
            ("feat(edm): filter sweep into bridge — edm-bassline", "marcus"),
            ("feat(harpsichord): feature/add-harpsichord — harpsichord replaces piano", "gabriel"),
            ("feat(harpsichord): double manual technique — feature/add-harpsichord", "pierre"),
            ("fix(voice-leading): parallel 5ths in bar 5 inner voices corrected", "gabriel"),
            ("refactor(form): add da capo repeat — bars 1-8 return at end", "gabriel"),
            ("feat(improv): jazz improvisation section — 8 bars over baroque changes", "marcus"),
            ("fix(timing): realign baroque ornaments to 16th grid", "gabriel"),
            ("feat(strings): add pizzicato baroque strings — bars 17-32", "sofia"),
            ("refactor(harmony): rewrite cadence — Phrygian half cadence, bar 16", "gabriel"),
            ("feat(coda): extended coda with fugal stretto — all voices", "gabriel"),
            ("fix(harpsichord): velocity normalization — harpsichord lacks dynamics", "gabriel"),
            ("feat(modal): modal interchange — borrow from D minor in bridge", "marcus"),
            ("refactor(mix): balance harpsichord vs bass — HF boost on harpsichord", "gabriel"),
            ("feat(ornament): mordent on beat 1 of each 4-bar phrase", "pierre"),
            ("feat(jazz2): jazz-voicings v2 — add upper-structure triads", "gabriel"),
            ("refactor(form): restructure to AABBA form — stronger contrast", "gabriel"),
            ("feat(bass): walking bass line for jazz-voicings bridge section", "marcus"),
            ("fix(modal): correct Dorian vs natural minor in bar 12", "gabriel"),
            ("feat(fugue): mini fugue in coda — 3-voice, 8 bars", "gabriel"),
        ],
        "jazz-chopin": [
            ("init: Jazz Chopin — Op.9 No.2 reharmonized, Bb minor at 68 BPM", "aaliya"),
            ("feat(reharmonize): tritone sub on V7 chord — bar 4", "aaliya"),
            ("feat(reharmonize): minor ii-V-I substitution in bridge", "gabriel"),
            ("feat(voicing): rootless 9th chord voicings — left hand", "aaliya"),
            ("feat(reharmonize): Coltrane substitution pattern in climax — reharmonized", "aaliya"),
            ("feat(reharmonize): add chromatic approach chords — reharmonized", "marcus"),
            ("feat(trio): trio-arrangement — add bass and drums", "aaliya"),
            ("feat(trio): walking bass added under reharmonized changes", "marcus"),
            ("feat(trio): brushed snare — light jazz feel, trio-arrangement", "gabriel"),
            ("fix(voice-leading): parallel 5ths in reharmonized bridge, bar 9", "aaliya"),
            ("refactor(melody): add bebop ornaments to Chopin melody line", "aaliya"),
            ("feat(reharmonize): backdoor ii-V substitution in outro", "aaliya"),
            ("fix(bass): fix intonation issue on low Bb — walking bass", "marcus"),
            ("feat(trio): piano solo chorus over jazz changes — trio-arrangement", "aaliya"),
            ("refactor(tempo): add ritardando at 4-bar phrase ends", "aaliya"),
            ("feat(reharmonize): modal interchange — iv chord from parallel minor", "gabriel"),
            ("fix(drums): remove unintentional kick on beat 3 — trio", "aaliya"),
            ("feat(coda): free improvisation coda — all three voices", "aaliya"),
            ("refactor(harmony): ensure all substitutions maintain melodic identity", "aaliya"),
            ("feat(reharmonize): full reharmonized version complete — all 3 sections", "aaliya"),
        ],
        "ragtime-edm": [
            ("init: Ragtime EDM — Maple Leaf Rag MIDI over trap beat at 128 BPM", "marcus"),
            ("feat(trap): trap hi-hat grid — 16th triplets with velocity variation", "marcus"),
            ("feat(trap): 808 kick on 1 and 3 — trap-version", "marcus"),
            ("feat(trap): snare on 2 and 4 with ghosted 16ths — trap-version", "gabriel"),
            ("feat(ragtime): ragtime melody quantized to EDM grid — bars 1-16", "marcus"),
            ("feat(house): house-version — 4-on-floor kick, Chicago-style", "marcus"),
            ("feat(house): sidechain compression on ragtime bass — house-version", "gabriel"),
            ("feat(house): filter sweep on ragtime melody — house-version", "marcus"),
            ("feat(swing): electro-swing branch — shuffle quantize 16ths to swing", "marcus"),
            ("feat(swing): brass sample layer on ragtime melody — electro-swing", "gabriel"),
            ("fix(pitch): transpose ragtime melody up one semitone to Ab for EDM mix", "marcus"),
            ("refactor(mix): sidechain bass to kick for pumping effect — all versions", "marcus"),
            ("feat(drop): big drop transition — silence then tutti return", "marcus"),
            ("fix(timing): tighten ragtime melody to EDM grid — was 10ms behind", "gabriel"),
            ("refactor(master): normalize to -8 LUFS for streaming platforms", "marcus"),
            ("feat(bridge): 8-bar bridge — minimal, just kick and ragtime melody fragment", "marcus"),
            ("feat(outro): outro — gradual filter close on all elements", "marcus"),
        ],
        "film-score": [
            ("init: Film Score — Act I, C (31-TET) — establishing motif, tense, pp", "chen"),
            ("feat(act1): act1 — microtonal string cluster, bars 1-8", "chen"),
            ("feat(act1): act1 — ascending quarter-tone figure in winds", "chen"),
            ("feat(act1): act1 — timpani accent on beat 3 — instability motif", "gabriel"),
            ("feat(act1): act1 — brass pedal — low brass drone, bars 9-16", "chen"),
            ("feat(act2): act2 branch — spectral climax, full orchestra tutti", "chen"),
            ("feat(act2): act2 — strings in high register, ff, sul ponticello", "sofia"),
            ("feat(act2): act2 — timpani rolls and brass fanfare — climax peak", "chen"),
            ("feat(act2): act2 — dissonant chord cluster, all 31-TET pitches", "gabriel"),
            ("feat(act3): act3 branch — resolution, return to simple C major", "chen"),
            ("feat(act3): act3 — solo violin melody, simple diatonic, pp", "sofia"),
            ("feat(act3): act3 — gradual orchestral return from silence", "chen"),
            ("feat(act3): act3 — final chord — C major, fff, held for 8 bars", "gabriel"),
            ("fix(tuning): recalibrate all instruments to 31-TET in Act I", "chen"),
            ("refactor(dynamics): smooth transition from Act I pp to Act II ff", "chen"),
            ("fix(voice-leading): remove dissonance clash in Act III resolution", "sofia"),
            ("refactor(score): add rehearsal letter marks every 8 bars", "chen"),
            ("feat(leitmotif): recurring motif appears in each act — unifying thread", "gabriel"),
        ],
        "polyrhythm": [
            ("init: Polyrhythm Studies — A minor at 92 BPM — 7-over-4 base", "fatou"),
            ("feat(7-4): 7-over-4 — djembe in 7, talking drum in 4", "fatou"),
            ("feat(7-4): 7-over-4 — bass guitar anchors common pulse", "fatou"),
            ("feat(7-4): 7-over-4 — listener orientation — hi-hat on beat 1 only", "aaliya"),
            ("refactor(7-4): humanize djembe timing — ±8ms variance", "fatou"),
            ("feat(5-3): 5-over-3-experiment — conga in 5, shekere in 3", "fatou"),
            ("feat(5-3): 5-over-3-experiment — bass anchors on shared beat", "aaliya"),
            ("feat(5-3): 5-over-3-experiment — add melody on shared downbeats only", "fatou"),
            ("fix(phase): fix drifting phase in 7-over-4 at bar 32 — MIDI timing", "fatou"),
            ("feat(groove): add cross-stick snare to bridge the two rhythmic worlds", "aaliya"),
            ("refactor(mix): bring up djembe attack — was buried under bass", "fatou"),
        ],
        "community": [
            ("init: Community Collab — open canvas — C major, 90 BPM", "gabriel"),
            ("feat(counterpoint): sofia's counterpoint — Bach-inspired 2-voice invention", "sofia"),
            ("feat(ornament): yuki's ornaments — granular delay on all voices", "yuki"),
            ("feat(analysis): pierre's analysis annotations — harmonic function labels", "pierre"),
            ("feat(bass): marcus's bassline — funk groove under baroque counterpoint", "marcus"),
            ("feat(rhythm): fatou's polyrhythm layer — 5-over-3 pattern over 4/4", "fatou"),
            ("feat(reharmonize): aaliya's jazz reharmonization of C major progression", "aaliya"),
            ("feat(microtonal): chen's microtonal ornaments — quarter-tone glissandi", "chen"),
            ("refactor(structure): gabriel rebalances all layers — new mix", "gabriel"),
            ("feat(baroque): sofia adds fugal episode — subject and answer", "sofia"),
            ("feat(texture): yuki adds granular texture layer — sparse grain scatter", "yuki"),
            ("fix(voice-leading): pierre fixes parallel 5ths — bars 12-13", "pierre"),
            ("feat(groove): marcus adds clavinet stabs — funk energy", "marcus"),
            ("feat(perc): fatou adds shekere pulse — holds everything together", "fatou"),
            ("feat(jazz): aaliya adds blue notes to melody — jazzy feel", "aaliya"),
            ("feat(tuning): chen corrects micro-tuning in ornament layer", "chen"),
            ("feat(improv): gabriel improvises bridge over new changes", "gabriel"),
            ("feat(strings): sofia adds lush string pad — bars 33-48", "sofia"),
            ("feat(reverb): yuki adds cathedral reverb to string layer", "yuki"),
            ("feat(harmony): pierre adds 9th and 11th extensions to all chords", "pierre"),
            ("feat(bass2): marcus doubles bassline at octave — thicker low end", "marcus"),
            ("feat(perc2): fatou adds djembe solo — bars 49-56", "fatou"),
            ("feat(modal): aaliya introduces Dorian mode shift in bridge", "aaliya"),
            ("feat(spectral): chen adds spectral filter sweep — act of transformation", "chen"),
            ("feat(motif): gabriel introduces 4-note motif — appears in all layers", "gabriel"),
            ("refactor(mix): sofia adjusts balance — counterpoint more prominent", "sofia"),
            ("feat(scatter): yuki reduces grain density for introspective section", "yuki"),
            ("feat(chorale): pierre writes 4-voice chorale climax — bars 57-64", "pierre"),
            ("feat(solo): marcus piano solo over baroque changes", "marcus"),
            ("feat(perc3): fatou polyrhythm climax — all layers simultaneously", "fatou"),
            ("feat(reprise): aaliya leads reprise of opening theme — reharmonized", "aaliya"),
            ("feat(finale): chen's finale motif — microtonal glissando into last chord", "chen"),
            ("feat(coda): gabriel's coda — reduces to solo piano, pp", "gabriel"),
            ("refactor(final-mix): sofia final mix pass — all dynamics balanced", "sofia"),
            ("feat(outro): yuki granular outro — voices dissolve into texture", "yuki"),
            ("feat(credits): pierre adds annotation — credits all contributors", "pierre"),
        ],
    }

    key = repo_key
    templates = TEMPLATES.get(key, TEMPLATES["neo-soul"])
    commits: list[dict[str, Any]] = []
    prev_id: str | None = None
    branch = "main"
    t = templates * ((n // len(templates)) + 1)

    for i in range(n):
        cid = _sha(f"{repo_id}-commit-{i}")
        msg = t[i % len(templates)][0]
        author = t[i % len(templates)][1]
        days = (n - i) * 2  # older commits further back
        commits.append(dict(
            commit_id=cid,
            repo_id=repo_id,
            branch=branch,
            parent_ids=[prev_id] if prev_id else [],
            message=msg,
            author=author,
            timestamp=_now(days=days),
            snapshot_id=_sha(f"snap-{repo_id}-{i}"),
        ))
        prev_id = cid
        # Sprinkle in a feature branch every ~8 commits
        if i > 0 and i % 8 == 0:
            branch = "main"

    return commits


# Track roles per repo key for the instrument breakdown bar
REPO_TRACKS: dict[str, list[tuple[str, str]]] = {
    "neo-soul":     [("bass", "tracks/bass.mid"), ("keys", "tracks/rhodes.mid"),
                     ("drums", "tracks/drums.mid"), ("strings", "tracks/strings.mid"),
                     ("horns", "tracks/trumpet.mid"), ("horns", "tracks/alto_sax.mid"),
                     ("guitar", "tracks/guitar.mid"), ("vocals", "tracks/vocals.mid")],
    "modal-jazz":   [("piano", "tracks/piano.mid"), ("bass", "tracks/bass.mid"),
                     ("drums", "tracks/drums.mid"), ("trumpet", "tracks/trumpet.mid"),
                     ("guitar", "tracks/guitar.mid")],
    "ambient":      [("pad", "tracks/pad.mid"), ("arp", "tracks/arpeggiator.mid"),
                     ("strings", "tracks/strings.mid"), ("bells", "tracks/bells.mid"),
                     ("drone", "tracks/drone.mid")],
    "afrobeat":     [("perc", "tracks/talking_drum.mid"), ("guitar", "tracks/guitar.mid"),
                     ("bass", "tracks/bass.mid"), ("horns", "tracks/horns.mid"),
                     ("keys", "tracks/rhodes.mid"), ("perc", "tracks/shekere.mid"),
                     ("vocals", "tracks/vocals.mid")],
    "microtonal":   [("piano", "tracks/piano.mid"), ("strings", "tracks/strings.mid"),
                     ("woodwinds", "tracks/woodwinds.mid"), ("perc", "tracks/percussion.mid")],
    "drums":        [("kick", "tracks/kick.mid"), ("snare", "tracks/snare.mid"),
                     ("hihat", "tracks/hihat.mid"), ("perc", "tracks/djembe.mid"),
                     ("808", "tracks/808.mid")],
    "chanson":      [("piano", "tracks/piano.mid"), ("cello", "tracks/cello.mid")],
    "granular":     [("pad", "tracks/granular_pad.mid"), ("texture", "tracks/texture.mid"),
                     ("rhythm", "tracks/rhythmic.mid")],
    "funk-suite":   [("bass", "tracks/bass.mid"), ("keys", "tracks/electric_piano.mid"),
                     ("clavinet", "tracks/clavinet.mid"), ("drums", "tracks/drums.mid"),
                     ("guitar", "tracks/guitar.mid"), ("horns", "tracks/horns.mid"),
                     ("perc", "tracks/congas.mid")],
    "jazz-trio":    [("piano", "tracks/piano.mid"), ("bass", "tracks/bass.mid"),
                     ("drums", "tracks/drums.mid")],
    # Genre archive repos — batch-13
    "wtc":              [("piano", "tracks/piano.mid"), ("harpsichord", "tracks/harpsichord.mid")],
    "goldberg":         [("piano", "tracks/piano.mid"), ("harpsichord", "tracks/harpsichord.mid")],
    "nocturnes":        [("piano", "tracks/piano.mid")],
    "maple-leaf":       [("piano", "tracks/piano.mid"), ("bass", "tracks/bass.mid")],
    "cinematic-strings":[("violin1", "tracks/violin1.mid"), ("violin2", "tracks/violin2.mid"),
                         ("viola", "tracks/viola.mid"), ("cello", "tracks/cello.mid"),
                         ("bass", "tracks/double_bass.mid"), ("timp", "tracks/timpani.mid")],
    "kai-ambient":      [("pad", "tracks/pad.mid"), ("piano", "tracks/piano.mid"),
                         ("strings", "tracks/strings.mid")],
    "neo-baroque":      [("harpsichord", "tracks/harpsichord.mid"), ("bass", "tracks/bass.mid"),
                         ("strings", "tracks/strings.mid")],
    "jazz-chopin":      [("piano", "tracks/piano.mid"), ("bass", "tracks/bass.mid"),
                         ("drums", "tracks/drums.mid")],
    "ragtime-edm":      [("piano", "tracks/piano.mid"), ("kick", "tracks/kick.mid"),
                         ("snare", "tracks/snare.mid"), ("hihat", "tracks/hihat.mid"),
                         ("808", "tracks/808.mid")],
    "film-score":       [("strings", "tracks/strings.mid"), ("brass", "tracks/brass.mid"),
                         ("woodwinds", "tracks/woodwinds.mid"), ("timp", "tracks/timpani.mid")],
    "polyrhythm":       [("djembe", "tracks/djembe.mid"), ("tama", "tracks/talking_drum.mid"),
                         ("shekere", "tracks/shekere.mid"), ("bass", "tracks/bass.mid")],
    "community":        [("piano", "tracks/piano.mid"), ("bass", "tracks/bass.mid"),
                         ("strings", "tracks/strings.mid"), ("perc", "tracks/djembe.mid"),
                         ("harpsichord", "tracks/harpsichord.mid"), ("pad", "tracks/granular_pad.mid")],
}

REPO_KEY_MAP = {
    REPO_NEO_SOUL:     "neo-soul",
    REPO_MODAL_JAZZ:   "modal-jazz",
    REPO_AMBIENT:      "ambient",
    REPO_AFROBEAT:     "afrobeat",
    REPO_MICROTONAL:   "microtonal",
    REPO_DRUM_MACHINE: "drums",
    REPO_CHANSON:      "chanson",
    REPO_GRANULAR:     "granular",
    REPO_FUNK_SUITE:   "funk-suite",
    REPO_JAZZ_TRIO:    "jazz-trio",
    REPO_NEO_SOUL_FORK: "neo-soul",
    REPO_AMBIENT_FORK:  "ambient",
    # Genre archive repos — batch-13
    REPO_WTC:          "wtc",
    REPO_GOLDBERG:     "goldberg",
    REPO_NOCTURNES:    "nocturnes",
    REPO_MAPLE_LEAF:   "maple-leaf",
    REPO_CIN_STRINGS:  "cinematic-strings",
    REPO_KAI_AMBIENT:  "kai-ambient",
    REPO_NEO_BAROQUE:  "neo-baroque",
    REPO_JAZZ_CHOPIN:  "jazz-chopin",
    REPO_RAGTIME_EDM:  "ragtime-edm",
    REPO_FILM_SCORE:   "film-score",
    REPO_POLYRHYTHM:   "polyrhythm",
    REPO_COMMUNITY:    "community",
}

COMMIT_COUNTS = {
    REPO_NEO_SOUL:     40,
    REPO_MODAL_JAZZ:   30,
    REPO_AMBIENT:      35,
    REPO_AFROBEAT:     38,
    REPO_MICROTONAL:   25,
    REPO_DRUM_MACHINE: 28,
    REPO_CHANSON:      22,
    REPO_GRANULAR:     24,
    REPO_FUNK_SUITE:   42,
    REPO_JAZZ_TRIO:    32,
    REPO_NEO_SOUL_FORK: 8,
    REPO_AMBIENT_FORK:  5,
    # Genre archive repos — batch-13
    REPO_WTC:          60,
    REPO_GOLDBERG:     35,
    REPO_NOCTURNES:    45,
    REPO_MAPLE_LEAF:   25,
    REPO_CIN_STRINGS:  30,
    REPO_KAI_AMBIENT:  20,
    REPO_NEO_BAROQUE:  55,
    REPO_JAZZ_CHOPIN:  40,
    REPO_RAGTIME_EDM:  35,
    REPO_FILM_SCORE:   28,
    REPO_POLYRHYTHM:   22,
    REPO_COMMUNITY:    70,
}

# Specific branch configurations for genre archive repos (batch-13).
# Each entry: list of (branch_name, commit_offset_from_end) — offset 0 = HEAD.
GENRE_REPO_BRANCHES: dict[str, list[tuple[str, int]]] = {
    REPO_WTC:         [("prelude-bk1", 50), ("fugue-bk1", 42), ("prelude-bk2", 20), ("fugue-bk2", 10)],
    REPO_GOLDBERG:    [("aria-only", 30), ("variation-13-experimental", 15)],
    REPO_NOCTURNES:   [("op9", 38), ("op15", 25), ("op27", 12)],
    REPO_MAPLE_LEAF:  [("slow-version", 10), ("marcus-edm-remix", 5)],
    REPO_CIN_STRINGS: [("orchestral", 20), ("stripped-piano", 8)],
    REPO_KAI_AMBIENT: [("v1", 14), ("v2-extended", 6)],
    REPO_NEO_BAROQUE: [("experiment/jazz-voicings", 45), ("experiment/edm-bassline", 30), ("feature/add-harpsichord", 15)],
    REPO_JAZZ_CHOPIN: [("reharmonized", 30), ("trio-arrangement", 15)],
    REPO_RAGTIME_EDM: [("trap-version", 28), ("house-version", 18), ("electro-swing", 8)],
    REPO_FILM_SCORE:  [("act1", 22), ("act2", 14), ("act3", 6)],
    REPO_POLYRHYTHM:  [("7-over-4", 16), ("5-over-3-experiment", 8)],
    REPO_COMMUNITY:   [("sofias-counterpoint", 60), ("yukis-ornaments", 50), ("pierres-analysis", 40), ("marcuss-bassline", 25)],
}


# ---------------------------------------------------------------------------
# Issue templates
# ---------------------------------------------------------------------------

ISSUE_TEMPLATES: dict[str, list[dict[str, Any]]] = {
    "neo-soul": [
        dict(n=1, state="open",   title="Bass line loses tension in bar 9",
             body="3-against-4 pulse drifts. Ghost note on beat 2.5 recommended.", labels=["groove", "bass"]),
        dict(n=2, state="open",   title="Add guitar scratch rhythm track",
             body="Arrangement too sparse. Scratch guitar would complement Rhodes.", labels=["arrangement"]),
        dict(n=3, state="closed", title="Tempo fluctuates bars 4-8",
             body="Resolved by re-quantizing with tight humanization.", labels=["tempo", "drums"]),
        dict(n=4, state="open",   title="Choir voicing too wide in chorus",
             body="Soprano and bass parts are 2+ octaves apart — muddy on small speakers.", labels=["harmony"]),
        dict(n=5, state="open",   title="Organ swell clashes with Rhodes",
             body="Both sit in mid-range 400-800Hz. Pan or EQ to separate.", labels=["mix"]),
        dict(n=6, state="closed", title="String pizzicato timing off",
             body="Fixed — re-quantized to 16th grid with 10ms humanize.", labels=["strings", "timing"]),
        dict(n=7, state="open",   title="Bridge needs more harmonic tension",
             body="The IV-I cadence in the bridge is too resolved. Try IV-bVII.", labels=["harmony", "bridge"]),
        dict(n=8, state="open",   title="Trumpet counter-melody too high",
             body="Goes above high C. Alto sax range would be more idiomatic.", labels=["horns"]),
        dict(n=9, state="closed", title="Bass note collision on beat 1",
             body="Fixed — root changed from F# to C# (5th) to reduce mud.", labels=["bass", "harmony"]),
        dict(n=10, state="open",  title="Add breakdown section before final chorus",
             body="Energy needs to drop before the big finish. 4-bar bass+drums only.", labels=["arrangement"]),
        dict(n=11, state="open",  title="Vocals too bright — needs de-essing",
             body="Sibilance prominent on headphones. High shelf cut above 10kHz.", labels=["mix", "vocals"]),
        dict(n=12, state="open",  title="Consider key change to A minor for outro",
             body="A modulation to relative major would give a brighter feel at the end.", labels=["harmony"]),
    ],
    "modal-jazz": [
        dict(n=1, state="open",   title="Phrygian bridge needs ii-V turnaround",
             body="Jump from D Dorian to E Phrygian is abrupt. Add Am7b5 → D7alt.", labels=["harmony"]),
        dict(n=2, state="open",   title="Swing factor inconsistent piano vs bass",
             body="Piano at 0.65 swing, bass at 0.55. Should match.", labels=["groove", "timing"]),
        dict(n=3, state="closed", title="Piano pedaling too heavy in changes",
             body="Fixed — reduced sustain pedal range.", labels=["piano"]),
        dict(n=4, state="open",   title="Guitar chord stabs too loud",
             body="Freddie Green stabs should sit under the piano. Lower -3dB.", labels=["mix", "guitar"]),
        dict(n=5, state="open",   title="Head melody needs resolution note",
             body="The A section ends on 6th scale degree — unresolved. Add scale degree 1.", labels=["melody"]),
        dict(n=6, state="open",   title="Tritone sub reharmonization too frequent",
             body="Using sub every 2 bars sounds formulaic. Reserve for 8-bar phrase end.", labels=["harmony"]),
        dict(n=7, state="closed", title="Bass solo too long — loses listener",
             body="Trimmed to 16 bars. Better pacing.", labels=["bass"]),
        dict(n=8, state="open",   title="Drummer needs to lay back on trumpet solo",
             body="Ride accent too prominent during solo. Comp more sparsely.", labels=["drums"]),
    ],
    "ambient": [
        dict(n=1, state="open",   title="Arpeggiator repeats — needs more variation",
             body="After 32 bars the pattern becomes predictable. Modulate seed every 8 bars.", labels=["generative"]),
        dict(n=2, state="open",   title="Pad too washy — needs more definition",
             body="Attack of 4s is too slow. Try 2s with a short sustain plateau.", labels=["pad"]),
        dict(n=3, state="closed", title="Stuck note in arp at bar 64",
             body="Fixed — MIDI note-off added. Was a gate issue.", labels=["bug", "midi"]),
        dict(n=4, state="open",   title="Add harmonic movement after bar 48",
             body="The Eb pedal has been static for 3 minutes. Move to Ab for 8 bars.", labels=["harmony"]),
        dict(n=5, state="open",   title="Norwegian church reverb is too bright",
             body="High frequency content in reverb tail is distracting. EQ pre-send.", labels=["mix"]),
        dict(n=6, state="open",   title="Granular density too high in intro",
             body="Start sparser and build. Currently too dense from bar 1.", labels=["texture"]),
        dict(n=7, state="closed", title="Phase correlation issues in stereo pad",
             body="Resolved by setting stereo width to 80% (was 120%).", labels=["mix"]),
        dict(n=8, state="open",   title="Piano melody needs more dynamic variation",
             body="All notes at same velocity. Add cresc/dim on each 4-bar phrase.", labels=["piano", "dynamics"]),
        dict(n=9, state="open",   title="Wind chimes pitched too high",
             body="7th partial sits above 8kHz on most speakers. Lower source pitch.", labels=["texture"]),
    ],
    "afrobeat": [
        dict(n=1, state="open",   title="Talking drum pattern needs more swing",
             body="Djembe is perfectly quantized — needs human timing ±5ms.", labels=["groove", "perc"]),
        dict(n=2, state="open",   title="Highlife guitar pattern clash with bass",
             body="Both emphasise beat 1. Guitar should accent beats 2 and 4.", labels=["arrangement"]),
        dict(n=3, state="closed", title="Conga timing drift at bar 32",
             body="Fixed — re-quantized to 8th note grid.", labels=["perc", "timing"]),
        dict(n=4, state="open",   title="Brass unison too thick — needs harmony",
             body="Four instruments in unison is thin. Split into 3-part harmony.", labels=["horns"]),
        dict(n=5, state="open",   title="Vocal call-and-response timing off",
             body="Response phrases enter 1 beat early. Needs 4-beat gap.", labels=["vocals"]),
        dict(n=6, state="open",   title="Add agogo bell pattern",
             body="The timeline/bell pattern is missing. Essential for afrobeat structure.", labels=["perc"]),
        dict(n=7, state="open",   title="Bass slap too clicky at high velocity",
             body="Velocities above 100 produce unwanted transient click.", labels=["bass"]),
        dict(n=8, state="closed", title="Organ swell level too high",
             body="Reduced by -4dB. Now sits correctly behind guitar.", labels=["mix"]),
        dict(n=9, state="open",   title="Yoruba lyric timing — stress on wrong syllable",
             body="Need input from native speaker on placement of tonal accent.", labels=["vocals", "cultural"]),
        dict(n=10, state="open",  title="Add Talking Heads-style guitar texture",
             body="Open-string plucked guitar arpeggio on top of the rhythm section.", labels=["guitar"]),
    ],
}

# Use a generic template for repos without specific issues
GENERIC_ISSUES = [
    dict(n=1, state="open",   title="Energy drops in the middle section",
         body="The arrangement loses momentum around bar 24-32. Add element to sustain interest.",
         labels=["arrangement", "energy"]),
    dict(n=2, state="open",   title="Dynamics too compressed",
         body="The quietest and loudest moments are within 3dB. Needs more dynamic range.",
         labels=["mix", "dynamics"]),
    dict(n=3, state="closed", title="Tempo inconsistency between sections",
         body="Fixed by applying strict quantize to all MIDI.", labels=["timing"]),
    dict(n=4, state="open",   title="Add a counter-melody",
         body="The main melody is unaccompanied for too long. Add a secondary voice.",
         labels=["arrangement"]),
    dict(n=5, state="open",   title="Harmonic rhythm too fast in verse",
         body="Chord changes every 2 beats feels rushed. Try 4-beat chord duration.",
         labels=["harmony"]),
    dict(n=6, state="closed", title="Mix: low end muddy",
         body="Resolved — high-pass filter below 80Hz on all non-bass instruments.",
         labels=["mix"]),
]


# ---------------------------------------------------------------------------
# PR templates
# ---------------------------------------------------------------------------

def _make_prs(repo_id: str, commits: list[dict[str, Any]], owner: str) -> list[dict[str, Any]]:
    if len(commits) < 4:
        return []
    c = commits
    return [
        dict(pr_id=_uid(f"pr-{repo_id}-1"), repo_id=repo_id,
             title="Feat: add counter-melody layer",
             body="## Changes\nAdds secondary melodic voice.\n\n## Analysis\nHarmonic tension +0.08.",
             state="open", from_branch="feat/counter-melody", to_branch="main",
             author=owner,
             created_at=_now(days=6)),
        dict(pr_id=_uid(f"pr-{repo_id}-2"), repo_id=repo_id,
             title="Refactor: humanize all MIDI timing",
             body="Applied `muse humanize --natural` to all tracks. Groove score +0.12.",
             state="merged", from_branch="fix/humanize-midi", to_branch="main",
             merge_commit_id=c[-3]["commit_id"],
             author=owner,
             created_at=_now(days=14)),
        dict(pr_id=_uid(f"pr-{repo_id}-3"), repo_id=repo_id,
             title="Experiment: alternate bridge harmony",
             body="Trying a tritone substitution approach for the bridge section.",
             state="open", from_branch="experiment/bridge-harmony", to_branch="main",
             author=owner,
             created_at=_now(days=3)),
        dict(pr_id=_uid(f"pr-{repo_id}-4"), repo_id=repo_id,
             title="Fix: resolve voice-leading errors",
             body="Parallel 5ths in bars 7-8 and parallel octaves in bars 15-16 corrected.",
             state="closed", from_branch="fix/voice-leading", to_branch="main",
             author=owner,
             created_at=_now(days=20)),
    ]


# ---------------------------------------------------------------------------
# Release templates
# ---------------------------------------------------------------------------

def _make_releases(repo_id: str, commits: list[dict[str, Any]], repo_name: str, owner: str) -> list[dict[str, Any]]:
    if not commits:
        return []
    return [
        dict(repo_id=repo_id, tag="v0.1.0", title="Early Draft",
             body=f"## v0.1.0 — Early Draft\n\nFirst checkpoint. Basic groove locked in.\n\n### Tracks\n- Main groove\n- Bass foundation\n\n### Technical\nInitial BPM and key established.",
             commit_id=commits[min(4, len(commits)-1)]["commit_id"],
             download_urls={"midi_bundle": f"/releases/{repo_id}-v0.1.0.zip"},
             author=owner,
             created_at=_now(days=45)),
        dict(repo_id=repo_id, tag="v0.2.0", title="Arrangement Draft",
             body=f"## v0.2.0 — Arrangement Draft\n\nAll major sections sketched.\n\n### What's new\n- Additional instrument layers\n- Section transitions defined\n- Dynamic arc mapped",
             commit_id=commits[min(12, len(commits)-1)]["commit_id"],
             download_urls={"midi_bundle": f"/releases/{repo_id}-v0.2.0.zip", "mp3": f"/releases/{repo_id}-v0.2.0.mp3"},
             author=owner,
             created_at=_now(days=25)),
        dict(repo_id=repo_id, tag="v1.0.0", title=f"{repo_name} — Full Release",
             body=f"## v1.0.0 — Full Release\n\nProduction-ready state.\n\n### Highlights\n- Complete arrangement with all instruments\n- Mixed and mastered\n- Stems included\n\n### Downloads\nMIDI bundle, MP3 stereo mix, individual stems",
             commit_id=commits[-1]["commit_id"],
             download_urls={"midi_bundle": f"/releases/{repo_id}-v1.0.0.zip",
                            "mp3": f"/releases/{repo_id}-v1.0.0.mp3",
                            "stems": f"/releases/{repo_id}-v1.0.0-stems.zip"},
             author=owner,
             created_at=_now(days=5)),
    ]


# ---------------------------------------------------------------------------
# Session templates
# ---------------------------------------------------------------------------

def _make_sessions(repo_id: str, owner: str, commits: list[dict[str, Any]]) -> list[dict[str, Any]]:
    if len(commits) < 2:
        return []
    sess = []
    collab_map: dict[str, list[tuple[str, ...]]] = {
        REPO_NEO_SOUL:     [("gabriel", "marcus"), ("gabriel",), ("gabriel", "marcus", "aaliya")],
        REPO_MODAL_JAZZ:   [("gabriel", "marcus"), ("gabriel",)],
        REPO_AMBIENT:      [("sofia", "yuki"), ("sofia",), ("sofia", "pierre")],
        REPO_AFROBEAT:     [("aaliya", "fatou"), ("aaliya",), ("aaliya", "marcus")],
        REPO_FUNK_SUITE:   [("marcus", "gabriel"), ("marcus",)],
        REPO_JAZZ_TRIO:    [("marcus",), ("marcus", "gabriel")],
        REPO_DRUM_MACHINE: [("fatou",), ("fatou", "aaliya")],
        REPO_CHANSON:      [("pierre",), ("pierre", "sofia")],
        REPO_GRANULAR:     [("yuki",), ("yuki", "sofia")],
        REPO_MICROTONAL:   [("chen",)],
    }
    collab_groups: list[tuple[str, ...]] = collab_map.get(repo_id) or [(owner,)]
    locations = [
        "Studio A, São Paulo", "Home studio", "Remote",
        "Abbey Road Studio 3", "Electric Lady Studios", "Remote (async)",
        "Bedroom studio, Tokyo", "La Fabrique, Marseille",
    ]
    for i, group in enumerate((collab_groups * 3)[:6]):
        start_days = 60 - i * 8
        dur_hours = [3, 4, 2, 5, 2, 3][i % 6]
        commit_slice = commits[i * 4:i * 4 + 3] if len(commits) > i * 4 + 3 else commits[-2:]
        sess.append(dict(
            session_id=_uid(f"sess-{repo_id}-{i}"),
            repo_id=repo_id,
            started_at=_now(days=start_days),
            ended_at=_now(days=start_days, hours=-dur_hours),
            participants=list(group),
            location=locations[i % len(locations)],
            intent=f"Session {i+1}: extend arrangement and refine mix",
            commits=[c["commit_id"] for c in commit_slice],
            notes=f"Productive session. Focused on {'groove' if i % 2 == 0 else 'arrangement'}.",
            is_active=False,
            created_at=_now(days=start_days),
        ))
    # Add one live/active session for the first big repo
    if repo_id in (REPO_NEO_SOUL, REPO_AFROBEAT):
        sess.append(dict(
            session_id=_uid(f"sess-{repo_id}-live"),
            repo_id=repo_id,
            started_at=_now(hours=1),
            ended_at=None,
            participants=[owner, "marcus"],
            location="Studio A — Live",
            intent="Live recording session — tracking final takes",
            commits=[],
            notes="",
            is_active=True,
            created_at=_now(hours=1),
        ))
    return sess


# ---------------------------------------------------------------------------
# Main seed function
# ---------------------------------------------------------------------------

async def seed(db: AsyncSession, force: bool = False) -> None:
    print("🌱 Seeding MuseHub stress-test dataset…")

    result = await db.execute(text("SELECT COUNT(*) FROM musehub_repos"))
    existing = result.scalar() or 0

    if existing > 0 and not force:
        print(f"  ⚠️  {existing} repo(s) already exist — skipping. Pass --force to wipe and reseed.")
        _print_urls()
        return

    if existing > 0 and force:
        print("  🗑  --force: clearing existing seed data…")
        for tbl in [
            "musehub_download_events", "musehub_view_events", "musehub_forks",
            "musehub_notifications", "musehub_watches", "musehub_follows",
            "musehub_reactions", "musehub_comments",
            "musehub_stars", "musehub_sessions", "musehub_releases",
            "musehub_webhook_deliveries", "musehub_webhooks",
            "musehub_pull_requests", "musehub_issues", "musehub_branches",
            "musehub_objects", "musehub_commits", "musehub_repos",
            "musehub_profiles",
        ]:
            await db.execute(text(f"DELETE FROM {tbl}"))
        await db.flush()

    # ── 1. User profiles ──────────────────────────────────────────
    all_user_profiles = list(USERS) + list(COMPOSER_USERS)
    for uid, uname, bio in all_user_profiles:
        db.add(MusehubProfile(
            user_id=uid,
            username=uname,
            bio=bio,
            avatar_url=f"https://api.dicebear.com/7.x/avataaars/svg?seed={uname}",
            pinned_repo_ids=[],
        ))
    print(f"  ✅ Profiles: {len(all_user_profiles)} users ({len(USERS)} community + {len(COMPOSER_USERS)} composer/archive)")

    # ── 2. Repos ──────────────────────────────────────────────────
    all_repos = list(REPOS) + list(GENRE_REPOS)
    for r in all_repos:
        db.add(MusehubRepo(
            repo_id=r["repo_id"],
            name=r["name"],
            owner=r["owner"],
            slug=r["slug"],
            owner_user_id=r["owner_user_id"],
            visibility=r["visibility"],
            description=r["description"],
            tags=r["tags"],
            key_signature=r["key_signature"],
            tempo_bpm=r["tempo_bpm"],
            created_at=_now(days=r["days_ago"]),
        ))
    print(f"  ✅ Repos: {len(all_repos)} ({len(REPOS)} original + {len(GENRE_REPOS)} genre archive)")

    await db.flush()

    # ── 3. Commits + Branches ─────────────────────────────────────
    all_commits: dict[str, list[dict[str, Any]]] = {}
    total_commits = 0
    for r in all_repos:
        repo_id = r["repo_id"]
        rkey = REPO_KEY_MAP.get(repo_id, "neo-soul")
        n = COMMIT_COUNTS.get(repo_id, 20)
        commits = _make_commits(repo_id, rkey, n)
        all_commits[repo_id] = commits
        total_commits += len(commits)
        for c in commits:
            db.add(MusehubCommit(**c))
        # main branch always points to HEAD
        db.add(MusehubBranch(repo_id=repo_id, name="main",
                             head_commit_id=commits[-1]["commit_id"]))
        if repo_id in GENRE_REPO_BRANCHES:
            # Genre archive repos: use specific named branches
            for branch_name, offset in GENRE_REPO_BRANCHES[repo_id]:
                idx = max(0, len(commits) - 1 - offset)
                db.add(MusehubBranch(
                    repo_id=repo_id,
                    name=branch_name,
                    head_commit_id=commits[idx]["commit_id"],
                ))
        else:
            # Original repos: generic feature branches
            if len(commits) > 10:
                db.add(MusehubBranch(repo_id=repo_id, name="feat/develop",
                                     head_commit_id=commits[-4]["commit_id"]))
            if len(commits) > 20:
                db.add(MusehubBranch(repo_id=repo_id, name="experiment/alternate-harmony",
                                     head_commit_id=commits[-8]["commit_id"]))
    print(f"  ✅ Commits: {total_commits} across {len(all_repos)} repos")

    await db.flush()

    # ── 4. Objects (track breakdown bar) ──────────────────────────
    obj_count = 0
    for r in all_repos:
        repo_id = r["repo_id"]
        rkey = REPO_KEY_MAP.get(repo_id, "neo-soul")
        tracks = REPO_TRACKS.get(rkey, REPO_TRACKS["neo-soul"])
        commits = all_commits.get(repo_id, [])
        if not commits:
            continue
        # Attach objects to the last 3 commits
        for commit in commits[-3:]:
            cid = commit["commit_id"]
            for role, path in tracks:
                obj_id = f"sha256:{_sha(f'{cid}-{path}')}"
                db.add(MusehubObject(
                    object_id=obj_id,
                    repo_id=repo_id,
                    path=path,
                    size_bytes=len(path) * 1024,
                    disk_path=f"/app/objects/{repo_id}/{obj_id[7:15]}.mid",
                    created_at=commit["timestamp"],
                ))
                obj_count += 1
    print(f"  ✅ Objects: {obj_count} track files")

    await db.flush()

    # ── 5. Issues ─────────────────────────────────────────────────
    issue_count = 0
    for r in all_repos:
        repo_id = r["repo_id"]
        rkey = REPO_KEY_MAP.get(repo_id, "neo-soul")
        issue_list = ISSUE_TEMPLATES.get(rkey, GENERIC_ISSUES)
        days_base = r["days_ago"]
        for iss in issue_list:
            db.add(MusehubIssue(
                repo_id=repo_id,
                number=iss["n"],
                state=iss["state"],
                title=iss["title"],
                body=iss["body"],
                labels=iss["labels"],
                author=r["owner"],
                created_at=_now(days=days_base - iss["n"] * 2),
            ))
            issue_count += 1
    print(f"  ✅ Issues: {issue_count}")

    await db.flush()

    # ── 6. Pull Requests ──────────────────────────────────────────
    pr_count = 0
    pr_ids: dict[str, list[str]] = {}
    for r in all_repos:
        repo_id = r["repo_id"]
        commits = all_commits.get(repo_id, [])
        prs = _make_prs(repo_id, commits, r["owner"])
        pr_ids[repo_id] = [p["pr_id"] for p in prs]
        for pr in prs:
            db.add(MusehubPullRequest(**pr))
            pr_count += 1
    print(f"  ✅ Pull Requests: {pr_count}")

    await db.flush()

    # ── 7. Releases ───────────────────────────────────────────────
    release_count = 0
    release_tags: dict[str, list[str]] = {}
    for r in all_repos:
        repo_id = r["repo_id"]
        commits = all_commits.get(repo_id, [])
        releases = _make_releases(repo_id, commits, r["name"], r["owner"])
        release_tags[repo_id] = [rel["tag"] for rel in releases]
        for rel in releases:
            db.add(MusehubRelease(**rel))
            release_count += 1
    print(f"  ✅ Releases: {release_count}")

    await db.flush()

    # ── 8. Sessions ───────────────────────────────────────────────
    session_count = 0
    session_ids: dict[str, list[str]] = {}
    for r in all_repos:
        repo_id = r["repo_id"]
        commits = all_commits.get(repo_id, [])
        sessions = _make_sessions(repo_id, r["owner"], commits)
        session_ids[repo_id] = [s["session_id"] for s in sessions]
        for sess in sessions:
            db.add(MusehubSession(**sess))
            session_count += 1
    print(f"  ✅ Sessions: {session_count}")

    await db.flush()

    # ── 9. Stars (cross-repo) ─────────────────────────────────────
    star_pairs = [
        (SOFIA,   REPO_NEO_SOUL, 20),    (MARCUS, REPO_NEO_SOUL, 18),
        (YUKI,    REPO_NEO_SOUL, 15),    (AALIYA, REPO_NEO_SOUL, 12),
        (CHEN,    REPO_NEO_SOUL, 10),    (FATOU,  REPO_NEO_SOUL, 8),
        (PIERRE,  REPO_NEO_SOUL, 6),

        (GABRIEL, REPO_AMBIENT, 14),     (MARCUS, REPO_AMBIENT, 12),
        (YUKI,    REPO_AMBIENT, 10),     (AALIYA, REPO_AMBIENT, 9),
        (CHEN,    REPO_AMBIENT, 7),      (FATOU,  REPO_AMBIENT, 5),
        (PIERRE,  REPO_AMBIENT, 3),

        (GABRIEL, REPO_AFROBEAT, 8),     (SOFIA,  REPO_AFROBEAT, 7),
        (MARCUS,  REPO_AFROBEAT, 6),     (YUKI,   REPO_AFROBEAT, 5),
        (CHEN,    REPO_AFROBEAT, 4),     (PIERRE, REPO_AFROBEAT, 3),

        (GABRIEL, REPO_FUNK_SUITE, 12),  (SOFIA,  REPO_FUNK_SUITE, 10),
        (AALIYA,  REPO_FUNK_SUITE, 9),   (CHEN,   REPO_FUNK_SUITE, 7),
        (FATOU,   REPO_FUNK_SUITE, 5),

        (GABRIEL, REPO_MODAL_JAZZ, 11),  (SOFIA,  REPO_MODAL_JAZZ, 8),
        (MARCUS,  REPO_MODAL_JAZZ, 6),   (AALIYA, REPO_MODAL_JAZZ, 4),

        (GABRIEL, REPO_JAZZ_TRIO, 9),    (SOFIA,  REPO_JAZZ_TRIO, 7),
        (AALIYA,  REPO_JAZZ_TRIO, 5),    (CHEN,   REPO_JAZZ_TRIO, 3),

        (GABRIEL, REPO_DRUM_MACHINE, 6), (MARCUS, REPO_DRUM_MACHINE, 4),
        (GABRIEL, REPO_GRANULAR, 5),     (MARCUS, REPO_GRANULAR, 3),
        (GABRIEL, REPO_CHANSON, 4),      (SOFIA,  REPO_CHANSON, 3),
        (GABRIEL, REPO_MICROTONAL, 3),   (SOFIA,  REPO_MICROTONAL, 2),
    ]
    for user_id, repo_id, days in star_pairs:
        db.add(MusehubStar(repo_id=repo_id, user_id=user_id,
                           created_at=_now(days=days)))
    print(f"  ✅ Stars: {len(star_pairs)}")

    await db.flush()

    # ── 10. Comments ─────────────────────────────────────────────
    COMMENT_BODIES = [
        "This groove is incredible — the 3-against-4 polyrhythm is exactly what this track needed.",
        "Love the Rhodes voicings here. Upper-structure triads give it that sophisticated neo-soul feel.",
        "The humanization really helped. Feels much more like a live performance now.",
        "I think the bridge needs more harmonic tension. The IV-I resolution is too settled.",
        "That trumpet counter-melody is stunning. It perfectly answers the Rhodes line.",
        "Could we push the bass a bit more? It's sitting a little behind the kick drum.",
        "The string pizzicato in the verse is a beautiful subtle touch.",
        "I'm not sure about the guitar scratch — feels a bit busy with the Rhodes.",
        "This is really coming together. The dynamic arc from intro to chorus is perfect.",
        "The call-and-response between horns and strings is very Quincy Jones.",
    ]

    comment_count = 0
    for r in REPOS[:6]:  # Comments on first 6 repos
        repo_id = r["repo_id"]
        commits = all_commits.get(repo_id, [])
        if not commits:
            continue
        # Comments on latest 3 commits
        for i, commit in enumerate(commits[-3:]):
            for j in range(3):
                body = COMMENT_BODIES[(i * 3 + j) % len(COMMENT_BODIES)]
                author_ids = [GABRIEL, SOFIA, MARCUS, YUKI, AALIYA, CHEN, FATOU, PIERRE]
                author = [u[1] for u in USERS if u[0] == author_ids[(i + j + hash(repo_id)) % len(author_ids)]][0]
                comment_id = _uid(f"comment-{repo_id}-{i}-{j}")
                db.add(MusehubComment(
                    comment_id=comment_id,
                    repo_id=repo_id,
                    target_type="commit",
                    target_id=commit["commit_id"],
                    author=author,
                    body=body,
                    parent_id=None,
                    created_at=_now(days=2, hours=i * 3 + j),
                ))
                comment_count += 1
                # Add a reply to first comment on each commit
                if j == 0:
                    reply_author = [u[1] for u in USERS if u[1] != author][0]
                    db.add(MusehubComment(
                        comment_id=_uid(f"reply-{repo_id}-{i}-{j}"),
                        repo_id=repo_id,
                        target_type="commit",
                        target_id=commit["commit_id"],
                        author=reply_author,
                        body="Totally agree — this part really elevates the whole track.",
                        parent_id=comment_id,
                        created_at=_now(days=1, hours=i * 2),
                    ))
                    comment_count += 1
    print(f"  ✅ Comments: {comment_count}")

    await db.flush()

    # ── 11. Reactions ─────────────────────────────────────────────
    EMOJIS = ["🔥", "🎵", "❤️", "👏", "✨", "🎸", "🎹", "🥁"]
    reaction_count = 0
    for r in REPOS[:6]:
        repo_id = r["repo_id"]
        commits = all_commits.get(repo_id, [])
        if not commits:
            continue
        for commit in commits[-5:]:
            for i, uid in enumerate([GABRIEL, SOFIA, MARCUS, YUKI, AALIYA]):
                emoji = EMOJIS[i % len(EMOJIS)]
                try:
                    db.add(MusehubReaction(
                        reaction_id=_uid(f"reaction-{repo_id}-{commit['commit_id'][:8]}-{uid}"),
                        repo_id=repo_id,
                        target_type="commit",
                        target_id=commit["commit_id"],
                        user_id=uid,
                        emoji=emoji,
                        created_at=_now(days=1),
                    ))
                    reaction_count += 1
                except Exception:
                    pass
    print(f"  ✅ Reactions: {reaction_count}")

    await db.flush()

    # ── 12. Follows (social graph) ────────────────────────────────
    follow_pairs = [
        (SOFIA, GABRIEL), (MARCUS, GABRIEL), (YUKI, GABRIEL),
        (AALIYA, GABRIEL), (CHEN, GABRIEL), (FATOU, GABRIEL),
        (GABRIEL, SOFIA), (MARCUS, SOFIA), (PIERRE, SOFIA),
        (GABRIEL, MARCUS), (SOFIA, MARCUS), (AALIYA, MARCUS),
        (GABRIEL, YUKI), (SOFIA, YUKI), (CHEN, YUKI),
        (GABRIEL, AALIYA), (MARCUS, AALIYA), (FATOU, AALIYA),
        (GABRIEL, CHEN), (YUKI, CHEN),
        (GABRIEL, FATOU), (AALIYA, FATOU),
        (GABRIEL, PIERRE), (SOFIA, PIERRE),
    ]
    for follower, followee in follow_pairs:
        db.add(MusehubFollow(
            follow_id=_uid(f"follow-{follower}-{followee}"),
            follower_id=follower,
            followee_id=followee,
            created_at=_now(days=15),
        ))
    print(f"  ✅ Follows: {len(follow_pairs)}")

    await db.flush()

    # ── 13. Watches ───────────────────────────────────────────────
    watch_pairs = [
        (GABRIEL, REPO_AMBIENT), (GABRIEL, REPO_AFROBEAT), (GABRIEL, REPO_FUNK_SUITE),
        (SOFIA, REPO_NEO_SOUL), (SOFIA, REPO_FUNK_SUITE), (SOFIA, REPO_CHANSON),
        (MARCUS, REPO_NEO_SOUL), (MARCUS, REPO_AMBIENT), (MARCUS, REPO_AFROBEAT),
        (YUKI, REPO_AMBIENT), (YUKI, REPO_GRANULAR), (YUKI, REPO_MICROTONAL),
        (AALIYA, REPO_NEO_SOUL), (AALIYA, REPO_AFROBEAT), (AALIYA, REPO_FUNK_SUITE),
        (CHEN, REPO_MICROTONAL), (CHEN, REPO_AMBIENT), (CHEN, REPO_GRANULAR),
        (FATOU, REPO_AFROBEAT), (FATOU, REPO_DRUM_MACHINE),
        (PIERRE, REPO_CHANSON), (PIERRE, REPO_AMBIENT),
    ]
    for user_id, repo_id in watch_pairs:
        db.add(MusehubWatch(
            watch_id=_uid(f"watch-{user_id}-{repo_id}"),
            user_id=user_id,
            repo_id=repo_id,
            created_at=_now(days=10),
        ))
    print(f"  ✅ Watches: {len(watch_pairs)}")

    await db.flush()

    # ── 14. Notifications ─────────────────────────────────────────
    EVENT_TYPES = ["comment", "pr_opened", "pr_merged", "issue_opened", "new_commit", "new_follower"]
    notif_count = 0
    for i, (uid, uname, _) in enumerate(USERS[:4]):
        for j in range(8):
            db.add(MusehubNotification(
                notif_id=_uid(f"notif-{uid}-{j}"),
                recipient_id=uid,
                event_type=EVENT_TYPES[j % len(EVENT_TYPES)],
                repo_id=REPOS[j % len(REPOS)]["repo_id"],
                actor=USERS[(i + j + 1) % len(USERS)][1],
                payload={"message": f"Sample notification {j+1} for {uname}"},
                is_read=j < 3,
                created_at=_now(days=j),
            ))
            notif_count += 1
    print(f"  ✅ Notifications: {notif_count}")

    await db.flush()

    # ── 15. Forks ─────────────────────────────────────────────────
    db.add(MusehubFork(
        fork_id=_uid("fork-neo-soul-marcus"),
        source_repo_id=REPO_NEO_SOUL,
        fork_repo_id=REPO_NEO_SOUL_FORK,
        forked_by="marcus",
        created_at=_now(days=10),
    ))
    db.add(MusehubFork(
        fork_id=_uid("fork-ambient-yuki"),
        source_repo_id=REPO_AMBIENT,
        fork_repo_id=REPO_AMBIENT_FORK,
        forked_by="yuki",
        created_at=_now(days=5),
    ))
    print("  ✅ Forks: 2")

    await db.flush()

    # ── 16. View events (analytics) ───────────────────────────────
    view_count = 0
    for r in REPOS[:8]:
        repo_id = r["repo_id"]
        for day_offset in range(30):
            date_str = (_now(days=day_offset)).strftime("%Y-%m-%d")
            viewers = r["star_count"] // 3 + 1
            for v in range(min(viewers, 10)):
                try:
                    db.add(MusehubViewEvent(
                        view_id=_uid(f"view-{repo_id}-{day_offset}-{v}"),
                        repo_id=repo_id,
                        viewer_fingerprint=_sha(f"viewer-{repo_id}-{v}"),
                        event_date=date_str,
                        created_at=_now(days=day_offset),
                    ))
                    view_count += 1
                except Exception:
                    pass
    print(f"  ✅ View events: {view_count}")

    await db.flush()

    # ── 17. Download events ───────────────────────────────────────
    dl_count = 0
    for r in REPOS[:6]:
        repo_id = r["repo_id"]
        for i in range(8):
            db.add(MusehubDownloadEvent(
                dl_id=_uid(f"dl-{repo_id}-{i}"),
                repo_id=repo_id,
                ref="main",
                downloader_id=[u[0] for u in USERS][i % len(USERS)],
                created_at=_now(days=i * 3),
            ))
            dl_count += 1
    print(f"  ✅ Download events: {dl_count}")

    await db.commit()
    print()
    _print_urls(all_commits, session_ids, pr_ids, release_tags)


def _print_urls(
    all_commits: dict[str, list[dict[str, Any]]] | None = None,
    session_ids: dict[str, list[str]] | None = None,
    pr_ids: dict[str, list[str]] | None = None,
    release_tags: dict[str, list[str]] | None = None,
) -> None:
    BASE = "http://localhost:10001/musehub/ui"
    print()
    print("=" * 72)
    print("🎵  MUSEHUB — ALL URLs (localhost:10001)")
    print("=" * 72)

    print("\n── User profiles ────────────────────────────────────────────────")
    for _, uname, _ in list(USERS) + list(COMPOSER_USERS):
        print(f"  {BASE}/users/{uname}")
        print(f"  {BASE}/{uname}  (redirects → above)")

    print("\n── Explore / discover ───────────────────────────────────────────")
    print(f"  {BASE}/explore")
    print(f"  {BASE}/trending")
    print(f"  {BASE}/search")
    print(f"  {BASE}/feed")

    all_repos_for_urls = list(REPOS[:8]) + list(GENRE_REPOS)
    for r in all_repos_for_urls:  # Skip fork repos from URL dump
        owner, slug = r["owner"], r["slug"]
        repo_id = r["repo_id"]
        rbase = f"{BASE}/{owner}/{slug}"

        print(f"\n── {owner}/{slug} ─────────────────────────────────────")
        print(f"  Repo:      {rbase}")
        print(f"  Graph:     {rbase}/graph")
        print(f"  Timeline:  {rbase}/timeline")
        print(f"  Insights:  {rbase}/insights")
        print(f"  Credits:   {rbase}/credits")
        print(f"  Search:    {rbase}/search")

        if all_commits and repo_id in all_commits:
            commits = all_commits[repo_id]
            for c in commits[-3:]:
                print(f"  Commit:    {rbase}/commits/{c['commit_id'][:12]}")
            if commits:
                print(f"  Diff:      {rbase}/commits/{commits[-1]['commit_id'][:12]}/diff")

        print(f"  Issues:    {rbase}/issues")
        print(f"  PRs:       {rbase}/pulls")
        print(f"  Releases:  {rbase}/releases")
        if release_tags and repo_id in release_tags:
            for tag in release_tags[repo_id]:
                print(f"             {rbase}/releases/{tag}")
        print(f"  Sessions:  {rbase}/sessions")
        if session_ids and repo_id in session_ids:
            for sid in session_ids[repo_id][:2]:
                print(f"             {rbase}/sessions/{sid}")
        print(f"  Divergence:{rbase}/divergence")
        print(f"  Context:   {rbase}/context/main")
        print(f"  Analysis:  {rbase}/analysis/main/contour")
        print(f"             {rbase}/analysis/main/tempo")
        print(f"             {rbase}/analysis/main/dynamics")

    print()
    print("=" * 72)
    print("✅  Seed complete.")
    print("=" * 72)


async def main() -> None:
    force = "--force" in sys.argv
    db_url: str = settings.database_url or ""
    engine = create_async_engine(db_url, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)  # type: ignore[call-overload]
    async with async_session() as db:
        await seed(db, force=force)
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
